"""Borrowed and threaded source contracts for the ParallelHash policy."""

BORROWED_TOKENS = {
    "execution/batch/scoped.rs": (
        "struct Output<'out>(&'out mut [[u8; 64]; CAPACITY])", "impl Drop for Output<'_>",
        "clear_owned_region(self.0.as_flattened_mut())", "clear_owned_region(output.0.as_flattened_mut())",
        "struct Scratch<'a>(&'a mut Workspace)", "self.0.clear()", "let scratch = Scratch(workspace)",
        "executor.kernel()?", "self.plan.job(index).map_err(plan_error)?.batch_input()",
        "executor.digest_secret(&inputs, destinations,", "brynja_core::copy_secret_region(destination, source)",
        "report.accelerated_slots & !active != 0", "executor.quarantine()",
        "!core::ptr::eq(plan, self.plan)", "merge(Err(ParallelHashError::LeafIdentity), &[])",
        "merge(index, &bytes[..$width])?", "Output<'out>", "PhantomData<Cell<()>>",
    ),
    "hardened_in_place/accelerated/scheduled.rs": (
        "sponge: api::$storage<'authority>, count: Count, stage: [u8;168]",
        "api::$storage::new(session)?", "self.sponge.report()", "let guard = CountGuard(count)",
        "let scratch = Block(scratch)", "Scheduled { state, scratch: &mut *scratch.0 }",
        "impl for<'scope> FnOnce($collector<'scope, 'plan, 'input, 'authority>) -> R",
        'sponge.with_bits(byte_string(b"ParallelHash")?', "plan.block_size(), plan.leaf_count()",
        "self.inner.merge(self.plan.checked_index(&result), result.expose())",
        "pub fn merge(&mut self, result: crate::$result<'plan, '_>)",
        "self.inner.public(output, valid)", "self.inner.secret(output, valid)", "Output::new(self.inner.xof()?)",
    ),
    "hardened_in_place/accelerated/scheduled_leaf.rs": (
        "sponge: api::$storage<'authority>", "api::$storage::new(session)?", "self.sponge.report()",
        "clear_owned_region(output)", "job.execute_with(output,", "state.finalize_bits_xof(input)?.squeeze_secret(output)",
    ),
    "hardened_in_place/accelerated/scheduled_backend.rs": (
        "self.state.update(&[])", "self.state.update(input)", "self.check()?",
        "Output::new(self.state.finalize_xof()?, self.scratch)", "clear_owned_region(output)", "Err(Error::StateConsumed)",
    ),
    "hardened_in_place/scheduled.rs": (
        "sponge: api::$storage, count: Count", "let guard = CountGuard(&mut self.count);",
        "impl for<'scope> FnOnce($collector<'scope, 'plan, 'input>) -> R",
        'self.sponge.with_bits(byte_string(b"ParallelHash")?', "plan.block_size(), plan.leaf_count()",
        "plan: &'plan crate::$plan<'input>", "self.inner.merge(self.plan.checked_index(&result), result.expose())",
        "pub fn merge(&mut self, result: crate::$result<'plan, '_>)",
        "self.inner.public(output, valid)", "self.inner.secret(output, valid)", "Output::new(self.inner.xof()?)",
    ),
    "hardened_in_place/scheduled_core.rs": (
        "count: &'scope mut Count", "state: Option<S>", "merged: [u8; 16]", "clear_owned_region(&mut self.merged)",
        "impl Drop for CountGuard<'_>", "self.0.wipe()", "self.count.wipe()", "self.state = None",
        "if !self.complete {", "self.collector.cancel()", "guard.collector.root()?.check()?",
        "index != read(&guard.collector.count.merged) || index >= guard.collector.expected",
        "index.checked_add(1)", "write(&mut guard.collector.count.merged, next)?",
        "read(&self.count.merged) != self.expected", "suffix.right(self.expected)?", "suffix.right(bits)?",
        "prefix.left(u128::try_from(block)", "clear_owned_region(output)", "self.finish(0)",
    ),
    "hardened_in_place/accelerated/xof.rs": (
        "inner: fixed::$fixed_workspace<'authority>", "inner: fixed::$fixed_state<'scope, 'authority>",
        "fixed::$fixed_workspace::new(root, leaf)?", "self.inner.root_report()", "self.inner.leaf_report()",
        "impl for<'scope> FnOnce($state<'scope, 'authority>) -> R",
        "self.inner.with(block, customization,", "self.inner.with_bits(block, customization,",
        "self.inner.with_scratch(block, customization, scratch,", "self.inner.with_bits_and_scratch(block, customization, scratch,",
        "self.inner.core.finish_xof(tail)?",
        "inner: Output<BackendOutput<api::$backend_reader<'scope, 'authority>, &'scope mut [u8]>>",
        "self.inner.public(output)", "self.inner.secret(output)", "self.inner.final_public(output, valid)",
        "self.inner.final_secret(output, valid)", "ParallelHashPublicDeclassification", "pub fn cancel(self)",
    ),
    "hardened_in_place/accelerated/fixed.rs": (
        "sponge: api::$storage<'authority>", "leaf: api::$leaf<'authority>", "metadata: Metadata", "stage: [u8;168]",
        "pub fn new(root: KeccakSession<'authority>, leaf: KeccakSession<'authority>)",
        "api::$storage::new(root)?", "api::$leaf::new(leaf)?",
        "impl for<'scope> FnOnce($state<'scope, 'authority>) -> R", "let cleanup = Guard(metadata);",
        "let scratch = Block(scratch);", "let block = Block(block);",
        'sponge.with_bits(byte_string(b"ParallelHash")?', "Backend { state, leaf, scratch: &mut *scratch.0 }",
        "self.core.public(tail, output, valid)", "self.core.secret(tail, output, valid)",
    ),
    "hardened_in_place/accelerated/backend.rs": (
        "self.state.update(&[])?", "self.leaf.with(|state| state.cancel())?", "self.check()?",
        "self.state.update(input)", "self.state.finalize_xof()?", "output.get_mut(..$size)",
        ".with(|state| state.finalize_bits_xof(input)?.squeeze_secret(bytes))?",
        "squeeze_final_bits_public(\n                        output,\n                        self.scratch,", "squeeze_final_bits_secret(output, valid)",
    ),
    "hardened_in_place/xof.rs": (
        "inner: fixed::$fixed_workspace", "inner: fixed::$fixed_state<'scope>",
        "impl for<'scope> FnOnce($state<'scope>) -> R", "self.inner.with_bits(block, customization,",
        "self.inner.core.finish_xof(tail)?", "inner: Output<api::$backend_reader<'scope>>",
        "self.inner.public(output)", "self.inner.secret(output)", "self.inner.final_public(output, valid)",
        "self.inner.final_secret(output, valid)", "ParallelHashPublicDeclassification", "pub fn cancel(self)",
    ),
    "hardened_in_place/reader.rs": (
        "reader: Option<R>", "reader: &'borrow mut Option<R>", "impl<R: Reader> Drop for Operation",
        "if !self.complete {", "*self.reader = None;", "guard.complete = true;",
        "clear_owned_region(output)", "self.reader.take().ok_or(Error::StateConsumed)?",
        "Fips202Output::new(output, valid)", "read_public(output)?", "read_secret(output)?",
        "#[cfg(test)]\nmod tests;",
    ),
    "hardened_in_place/fixed.rs": (
        "sponge: api::$storage, metadata: Metadata", "pub fn new() -> Self",
        "impl for<'scope> FnOnce($state<'scope>) -> R", "let metadata = Guard(&mut self.metadata);",
        "let block = Block(block);", 'self.sponge.with_bits(byte_string(b"ParallelHash")?',
        "Core::new(state, &mut *metadata.0, &mut *block.0)?",
        "self.core.public(tail, output, valid)", "self.core.secret(tail, output, valid)",
        "pub fn finalize_bits_secret<'out>(self,", "ParallelHashPublicDeclassification", "pub fn cancel(self)",
    ),
    "hardened_in_place/core_state.rs": (
        "state: Option<S>", "metadata: &'scope mut Metadata", "block: &'scope mut [u8]",
        "clear_owned_region(&mut self.used)", "clear_owned_region(&mut self.leaves)", "clear_owned_region(&mut self.leaf)",
        "impl Drop for Guard<'_>", "impl Drop for Block<'_>", "self.state = None;", "if !self.complete {",
        "self.core.cancel();", "operation.complete = true;", "prefix.left(", "suffix.right(read(&self.metadata.leaves))?",
        "suffix.right(output_bits)?", "state.leaf(bits, &mut self.metadata.leaf)?", "update(secret.expose())?",
        "operation.core.root()?.check()?", "self.root()?.check()?",
        "clear_owned_region(output)", "Fips202Output::new(output, valid)", "self.state.take().ok_or(Error::StateConsumed)?.finish()",
        "self.flush(tail.valid_bits_in_last_byte())", "u128::try_from(full)",
        "pub(super) fn finish_xof(mut self,", "self.finish(tail, 0)",
    ),
    "hardened_in_place/backend.rs": (
        "impl<'scope> State for api::$state<'scope>", "self.finalize_xof()",
        "crate::backend::$leaf(input,", "Fips202Output::new(output, valid)",
        "Sha3PublicDeclassification::acknowledge()",
    ),
    "secret_encoding.rs": (
        "pub(crate) const fn empty() -> Self", "pub(crate) fn left(&mut self,", "pub(crate) fn right(&mut self,",
        "clear_owned_region(storage)", "clear_owned_region(length)", "!(2..=17).contains(&count)",
        "clear_owned_region(&mut self.bytes)", "clear_owned_region(&mut self.length)",
        "let marker = if left { 0 } else { width }", ".checked_add(usize::from(left))",
    ),
    "core_state.rs": ("let mut prefix = Encoded::empty();", "prefix.left(block_size)?", "suffix.right(self.leaf_count())?", "suffix.right(output_bits)?",
        "brynja_core::copy_secret_region(target, source)",
        "let byte = bytes.last().ok_or(ParallelHashError::InvalidBitString)?;",
        "core::slice::from_mut(target)", "core::slice::from_ref(byte)"),
    "scheduled.rs": ("let mut prefix = Encoded::empty();", "prefix.left(block)?", "suffix.right(self.expected)?", "suffix.right(output_bits)?",
        "pub(crate) fn checked_index", "!core::ptr::eq(identity, &self.identity)",
        "count != self.leaves", "block != self.block_size", "pub(crate) fn execute_with",
        "operation(self.input, output)", "identity: self.identity"),
    "execution/encoding.rs": ("pub(super) const fn empty() -> Self", "pub(super) fn left(&mut self,", "pub(super) fn right(&mut self,",
        "crate::secret_encoding::write(&mut self.bytes, &mut self.length, value, true)",
        "crate::secret_encoding::write(&mut self.bytes, &mut self.length, value, false)",
        "crate::secret_encoding::bytes(&self.bytes, &self.length)",
        "clear_owned_region(&mut self.bytes)", "clear_owned_region(&mut self.length)"),
    "execution/collector.rs": ("prefix.left(block)?", "suffix.right(root.merged_leaves())?", "suffix.right(output_bits)?"),
    "backend.rs": ("hardened_in_place::Shake128Workspace::new()", "hardened_in_place::Shake256Workspace::new()",
        "workspace.with(|state| state.finalize_bits_xof(input)?.squeeze_secret(output))"),
}

SCOPED_THREAD_TOKENS = {
    "strict_execution/mod.rs": (
        "ProtectedStack::new(limits.stack_bytes, limits.max_stack_mapping_bytes)?",
        "let cvs = ProtectedBytes::new(cv_bytes, limits.max_buffer_mapping_bytes)?",
        "let mut buffers = Buffers", "self.cvs.clear()", "self.staging.clear()", "self.output.clear()",
        "if !self.keep", "buffers.keep = true", "#[cfg(test)]\nmod tests;",
    ),
    "strict_execution/worker.rs": (
        "root.run(||", "ProtectedStack::run_group(", "output.take().ok_or(Error::Invariant)?",
        "let plan = &plan", "let mut workspace = scoped::$workspace::new()",
        "collector", ".merge(result.take().ok_or(Error::Invariant)??)",
        "brynja_core::copy_secret_region(destination, source)",
        "check(cancel)?", ".try_reserve_exact(count)",
    ),
    "execution/batch/in_place.rs": ("let scratch = Scratch(scratch)", "let _gate = self.inner.base.gate()?",
        "clear_owned_region(output)", "brynja_core::copy_secret_region(output, secret.expose())", "root.merge_batch(leaves)",
        "Selection::new(self.inner.base.config.root)?", "plan.leaf_count() > self.inner.base.config.max_leaves",
        "accelerated::$workspace::new(session).map_err(crypto)?", "#[cfg(test)]\nmod tests;"),
    "execution/batch/in_place/worker.rs": ("struct GroupSlots(Vec<[[u8; 64]; leaf::CAPACITY]>)",
        "try_reserve_exact(length)", "clear_owned_region(slot.as_flattened_mut())", "self.clear()",
        "GroupSlots::new(width)?", "thread::scope(|scope|", "match handle.join()", "if failure.is_none()",
        "Selection::new(executor.inner.base.config.leaves)?", "leaf::Workspace::new()",
        "leaf::Control::new(executor.inner.budget, &mut cancel)", "merge(leaves).map_err(crypto)",
        "failure.map_or(Ok(work), Err)", "#[cfg(test)]\nmod tests;"),
    "in_place.rs": ("let _gate = self.enter_operation()?", "crate::scoped_worker::admit(",
        "workspace.with_bits(plan, customization, |mut root|", "|leaf| root.merge(leaf)",
        "crate::worker::ensure_live(cancellation)?", "Ok(operation(root))",
        "impl for<'scope> FnOnce(api::$collector<'scope, 'plan, 'input>) -> R"),
    "scoped_worker.rs": ("struct Slots<const N: usize>(pub(crate) Vec<[u8; N]>)", "try_reserve_exact(length)",
        "clear_owned_region(slot)", "self.clear()", "Slots::<$width>::new(leaves.min(workers))",
        "base.checked_add(count)", "base.checked_add(offset)", "if leaves > limit",
        "thread::scope(|scope|", "try_reserve_exact(batch.len())", "match handle.join()",
        "if failure.is_none()", "ensure_live(cancel)?", "let result = job.execute(destination)?",
        "failure.map_or(Ok(()), Err)", "#[cfg(test)]\nmod tests;"),
    "execution/in_place.rs": ("let scratch = Scratch(scratch)", "let _gate = self.inner.gate()?",
        "clear_owned_region(output)", "brynja_core::copy_secret_region(output, secret.expose())", "live(cancellation)?",
        "Selection::new(self.inner.config.root)?", "plan.leaf_count() > self.inner.config.max_leaves",
        ".with_bits(&plan, request.customization, |mut root|", "|leaf| root.merge(leaf)",
        "accelerated::$workspace::new(session).map_err(crypto)?", "Mode::Require(None) => Err(Error::Unavailable)",
        ".squeeze_final_bits_secret(output, valid)", "root.finalize_secret_bits(output, valid)"),
    "execution/in_place/worker.rs": ("Slots::<$width>::new(leaves.min(config.workers))", "if failure.is_none()",
        "Selection::new(preference)?", "let result = $leaf(job, destination, &owner)?", "match handle.join()",
        "accelerated.checked_add(used)", ".checked_add(u128::from(used))", "merge(leaf).map_err(crypto)?",
        "workspace.execute(job, output).map_err(crypto)?", "Mode::Require(None) => Err(Error::Unavailable)",
        "clear_owned_region(output)", "live(cancellation)?", "failure.map_or(Ok(accelerated), Err)"),
}
