[package]
name = "brynja-tls13"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"
description = "Version-specific TLS 1.3 stream engine for Brynja"
publish = false

[features]
default = []

[dependencies]
brynja-core = { workspace = true }
brynja-crypto = { workspace = true }
brynja-tls13-handshake = { workspace = true }

[lints]
workspace = true
