//! Packed Keccak-f[1600] with a single opaque AVX2 cleanup boundary.
#![allow(unsafe_code)]

/// Permute four lanes in bytes 0..800; erase non-output scratch and working registers.
/// Caller packing, caller copies and asynchronous interruption are separate.
///
/// # Safety
/// AVX2 and OS-enabled YMM state must remain available on every eligible CPU throughout the call.
#[target_feature(enable = "avx2")]
#[inline(never)]
pub unsafe extern "C" fn permute(scratch: &mut [u8; 1920], constants: &[u64; 24]) {
    const {
        assert!(cfg!(target_endian = "little"));
    }
    // SAFETY: Scratch consists of 25 state words (0..800), five column words
    // (800..960), five deltas (960..1120) and 25 staging words (1120..1920),
    // each with a 32-byte stride. Fixed rho/pi and chi offsets stay in these
    // initialized exclusive regions. Public loops visit columns 0..160 by 32,
    // rows 0..800 by 160 and constants 0..192 by 8. Unaligned accesses fit.
    // All four 64-bit lanes are independent.
    // The sole side-effecting block contains all secret operations, no stack
    // accesses or calls, and no Rust secret outputs. It erases 800..1920 and
    // RAX/RCX/RDX, YMM0..3, then flags. Early clobbers exclude both pointers;
    // Win64 XMM6..15 are untouched. No instruction needs a stronger ISA.
    unsafe {
        core::arch::asm!(
            "# BRYNJA_SECRET_BEGIN",
            "xor eax, eax",
            "2:",
            "xor ecx, ecx",
            "3:",
            "vmovdqu ymm0, [{scratch} + rcx]",
            "vpxor ymm0, ymm0, [{scratch} + rcx + 160]",
            "vpxor ymm0, ymm0, [{scratch} + rcx + 320]",
            "vpxor ymm0, ymm0, [{scratch} + rcx + 480]",
            "vpxor ymm0, ymm0, [{scratch} + rcx + 640]",
            "vmovdqu [{scratch} + rcx + 800], ymm0",
            "add rcx, 32",
            "cmp rcx, 160",
            "jne 3b",
            "vmovdqu ymm0, [{scratch} + 832]",
            "vpsllq ymm1, ymm0, 1",
            "vpsrlq ymm0, ymm0, 63",
            "vpor ymm0, ymm0, ymm1",
            "vpxor ymm0, ymm0, [{scratch} + 928]",
            "vmovdqu [{scratch} + 960], ymm0",
            "vmovdqu ymm0, [{scratch} + 864]",
            "vpsllq ymm1, ymm0, 1",
            "vpsrlq ymm0, ymm0, 63",
            "vpor ymm0, ymm0, ymm1",
            "vpxor ymm0, ymm0, [{scratch} + 800]",
            "vmovdqu [{scratch} + 992], ymm0",
            "vmovdqu ymm0, [{scratch} + 896]",
            "vpsllq ymm1, ymm0, 1",
            "vpsrlq ymm0, ymm0, 63",
            "vpor ymm0, ymm0, ymm1",
            "vpxor ymm0, ymm0, [{scratch} + 832]",
            "vmovdqu [{scratch} + 1024], ymm0",
            "vmovdqu ymm0, [{scratch} + 928]",
            "vpsllq ymm1, ymm0, 1",
            "vpsrlq ymm0, ymm0, 63",
            "vpor ymm0, ymm0, ymm1",
            "vpxor ymm0, ymm0, [{scratch} + 864]",
            "vmovdqu [{scratch} + 1056], ymm0",
            "vmovdqu ymm0, [{scratch} + 800]",
            "vpsllq ymm1, ymm0, 1",
            "vpsrlq ymm0, ymm0, 63",
            "vpor ymm0, ymm0, ymm1",
            "vpxor ymm0, ymm0, [{scratch} + 896]",
            "vmovdqu [{scratch} + 1088], ymm0",
            "vmovdqu ymm0, [{scratch} + 0]",
            "vpxor ymm0, ymm0, [{scratch} + 960]",
            "vmovdqu [{scratch} + 1120], ymm0",
            "vmovdqu ymm0, [{scratch} + 32]",
            "vpxor ymm0, ymm0, [{scratch} + 992]",
            "vpsllq ymm1, ymm0, 1",
            "vpsrlq ymm0, ymm0, 63",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1440], ymm0",
            "vmovdqu ymm0, [{scratch} + 64]",
            "vpxor ymm0, ymm0, [{scratch} + 1024]",
            "vpsllq ymm1, ymm0, 62",
            "vpsrlq ymm0, ymm0, 2",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1760], ymm0",
            "vmovdqu ymm0, [{scratch} + 96]",
            "vpxor ymm0, ymm0, [{scratch} + 1056]",
            "vpsllq ymm1, ymm0, 28",
            "vpsrlq ymm0, ymm0, 36",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1280], ymm0",
            "vmovdqu ymm0, [{scratch} + 128]",
            "vpxor ymm0, ymm0, [{scratch} + 1088]",
            "vpsllq ymm1, ymm0, 27",
            "vpsrlq ymm0, ymm0, 37",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1600], ymm0",
            "vmovdqu ymm0, [{scratch} + 160]",
            "vpxor ymm0, ymm0, [{scratch} + 960]",
            "vpsllq ymm1, ymm0, 36",
            "vpsrlq ymm0, ymm0, 28",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1632], ymm0",
            "vmovdqu ymm0, [{scratch} + 192]",
            "vpxor ymm0, ymm0, [{scratch} + 992]",
            "vpsllq ymm1, ymm0, 44",
            "vpsrlq ymm0, ymm0, 20",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1152], ymm0",
            "vmovdqu ymm0, [{scratch} + 224]",
            "vpxor ymm0, ymm0, [{scratch} + 1024]",
            "vpsllq ymm1, ymm0, 6",
            "vpsrlq ymm0, ymm0, 58",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1472], ymm0",
            "vmovdqu ymm0, [{scratch} + 256]",
            "vpxor ymm0, ymm0, [{scratch} + 1056]",
            "vpsllq ymm1, ymm0, 55",
            "vpsrlq ymm0, ymm0, 9",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1792], ymm0",
            "vmovdqu ymm0, [{scratch} + 288]",
            "vpxor ymm0, ymm0, [{scratch} + 1088]",
            "vpsllq ymm1, ymm0, 20",
            "vpsrlq ymm0, ymm0, 44",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1312], ymm0",
            "vmovdqu ymm0, [{scratch} + 320]",
            "vpxor ymm0, ymm0, [{scratch} + 960]",
            "vpsllq ymm1, ymm0, 3",
            "vpsrlq ymm0, ymm0, 61",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1344], ymm0",
            "vmovdqu ymm0, [{scratch} + 352]",
            "vpxor ymm0, ymm0, [{scratch} + 992]",
            "vpsllq ymm1, ymm0, 10",
            "vpsrlq ymm0, ymm0, 54",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1664], ymm0",
            "vmovdqu ymm0, [{scratch} + 384]",
            "vpxor ymm0, ymm0, [{scratch} + 1024]",
            "vpsllq ymm1, ymm0, 43",
            "vpsrlq ymm0, ymm0, 21",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1184], ymm0",
            "vmovdqu ymm0, [{scratch} + 416]",
            "vpxor ymm0, ymm0, [{scratch} + 1056]",
            "vpsllq ymm1, ymm0, 25",
            "vpsrlq ymm0, ymm0, 39",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1504], ymm0",
            "vmovdqu ymm0, [{scratch} + 448]",
            "vpxor ymm0, ymm0, [{scratch} + 1088]",
            "vpsllq ymm1, ymm0, 39",
            "vpsrlq ymm0, ymm0, 25",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1824], ymm0",
            "vmovdqu ymm0, [{scratch} + 480]",
            "vpxor ymm0, ymm0, [{scratch} + 960]",
            "vpsllq ymm1, ymm0, 41",
            "vpsrlq ymm0, ymm0, 23",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1856], ymm0",
            "vmovdqu ymm0, [{scratch} + 512]",
            "vpxor ymm0, ymm0, [{scratch} + 992]",
            "vpsllq ymm1, ymm0, 45",
            "vpsrlq ymm0, ymm0, 19",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1376], ymm0",
            "vmovdqu ymm0, [{scratch} + 544]",
            "vpxor ymm0, ymm0, [{scratch} + 1024]",
            "vpsllq ymm1, ymm0, 15",
            "vpsrlq ymm0, ymm0, 49",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1696], ymm0",
            "vmovdqu ymm0, [{scratch} + 576]",
            "vpxor ymm0, ymm0, [{scratch} + 1056]",
            "vpsllq ymm1, ymm0, 21",
            "vpsrlq ymm0, ymm0, 43",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1216], ymm0",
            "vmovdqu ymm0, [{scratch} + 608]",
            "vpxor ymm0, ymm0, [{scratch} + 1088]",
            "vpsllq ymm1, ymm0, 8",
            "vpsrlq ymm0, ymm0, 56",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1536], ymm0",
            "vmovdqu ymm0, [{scratch} + 640]",
            "vpxor ymm0, ymm0, [{scratch} + 960]",
            "vpsllq ymm1, ymm0, 18",
            "vpsrlq ymm0, ymm0, 46",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1568], ymm0",
            "vmovdqu ymm0, [{scratch} + 672]",
            "vpxor ymm0, ymm0, [{scratch} + 992]",
            "vpsllq ymm1, ymm0, 2",
            "vpsrlq ymm0, ymm0, 62",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1888], ymm0",
            "vmovdqu ymm0, [{scratch} + 704]",
            "vpxor ymm0, ymm0, [{scratch} + 1024]",
            "vpsllq ymm1, ymm0, 61",
            "vpsrlq ymm0, ymm0, 3",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1408], ymm0",
            "vmovdqu ymm0, [{scratch} + 736]",
            "vpxor ymm0, ymm0, [{scratch} + 1056]",
            "vpsllq ymm1, ymm0, 56",
            "vpsrlq ymm0, ymm0, 8",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1728], ymm0",
            "vmovdqu ymm0, [{scratch} + 768]",
            "vpxor ymm0, ymm0, [{scratch} + 1088]",
            "vpsllq ymm1, ymm0, 14",
            "vpsrlq ymm0, ymm0, 50",
            "vpor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 1248], ymm0",
            "xor ecx, ecx",
            "4:",
            "vmovdqu ymm0, [{scratch} + rcx + 1152]",
            "vpandn ymm0, ymm0, [{scratch} + rcx + 1184]",
            "vpxor ymm0, ymm0, [{scratch} + rcx + 1120]",
            "vmovdqu [{scratch} + rcx + 0], ymm0",
            "vmovdqu ymm0, [{scratch} + rcx + 1184]",
            "vpandn ymm0, ymm0, [{scratch} + rcx + 1216]",
            "vpxor ymm0, ymm0, [{scratch} + rcx + 1152]",
            "vmovdqu [{scratch} + rcx + 32], ymm0",
            "vmovdqu ymm0, [{scratch} + rcx + 1216]",
            "vpandn ymm0, ymm0, [{scratch} + rcx + 1248]",
            "vpxor ymm0, ymm0, [{scratch} + rcx + 1184]",
            "vmovdqu [{scratch} + rcx + 64], ymm0",
            "vmovdqu ymm0, [{scratch} + rcx + 1248]",
            "vpandn ymm0, ymm0, [{scratch} + rcx + 1120]",
            "vpxor ymm0, ymm0, [{scratch} + rcx + 1216]",
            "vmovdqu [{scratch} + rcx + 96], ymm0",
            "vmovdqu ymm0, [{scratch} + rcx + 1120]",
            "vpandn ymm0, ymm0, [{scratch} + rcx + 1152]",
            "vpxor ymm0, ymm0, [{scratch} + rcx + 1248]",
            "vmovdqu [{scratch} + rcx + 128], ymm0",
            "add rcx, 160",
            "cmp rcx, 800",
            "jne 4b",
            "vpbroadcastq ymm0, [{constants} + rax]",
            "vpxor ymm0, ymm0, [{scratch}]",
            "vmovdqu [{scratch}], ymm0",
            "add rax, 8",
            "cmp rax, 192",
            "jne 2b",
            "vpxor ymm0, ymm0, ymm0",
            "mov ecx, 800",
            "5:",
            "vmovdqu [{scratch} + rcx], ymm0",
            "add rcx, 32",
            "cmp rcx, 1920",
            "jne 5b",
            "# BRYNJA_REGISTER_ERASE",
            "xor eax, eax",
            "xor ecx, ecx",
            "xor edx, edx",
            "vpxor ymm0, ymm0, ymm0",
            "vpxor ymm1, ymm1, ymm1",
            "vpxor ymm2, ymm2, ymm2",
            "vpxor ymm3, ymm3, ymm3",
            "cmp eax, eax",
            "# BRYNJA_SECRET_END",
            scratch = in(reg) scratch.as_mut_ptr(),
            constants = in(reg) constants.as_ptr(),
            out("rax") _,
            out("rcx") _,
            out("rdx") _,
            out("ymm0") _,
            out("ymm1") _,
            out("ymm2") _,
            out("ymm3") _,
            options(nostack),
        );
    }
}
