//! Opaque legacy SHA-1 compression; SHA-1 remains collision-broken.
#![allow(unsafe_code)]

/// Compress one block; retain only chaining output and erase the schedule.
/// Caller buffers/copies, framing and asynchronous interruption are separate.
///
/// # Safety
/// The complete neon,sha2 bundle must remain available on every eligible CPU.
/// All three borrows must refer to distinct, initialized live regions.
#[target_feature(enable = "neon,sha2")]
#[inline(never)]
pub unsafe extern "C" fn compress(
    state: &mut [u8; 20],
    block: &[u8; 64],
    schedule: &mut [u8; 320],
) {
    // SAFETY: Exact byte arrays bound all unaligned accesses. State loads cover
    // 0..16 plus 16..20 only; block loads cover 0..64. Twenty 16-byte schedule
    // groups hold the four-word recurrence and all eighty rounds. Addresses and
    // branches depend only on fixed offsets or public counters. Endian conversion,
    // expansion, rounds and feed-forward stay inside one side-effecting block,
    // with no stack access, calls or Rust secret outputs. The entire schedule,
    // X4/X5/X6 and V0..5 and flags are erased before normal return. Early clobbers
    // exclude the pointers; ABI-preserved D8..15 are untouched.
    unsafe {
        core::arch::asm!(
            "// BRYNJA_SECRET_BEGIN",
            "mov x4, #0",
            "2:",
            "add x5, {block}, x4",
            "ldr q3, [x5]",
            "rev32 v3.16b, v3.16b",
            "add x5, {schedule}, x4",
            "str q3, [x5]",
            "add x4, x4, #16",
            "cmp x4, #64",
            "b.ne 2b",
            "mov x4, #64",
            "3:",
            "add x5, {schedule}, x4",
            "ldur q3, [x5, #-64]",
            "ldur q4, [x5, #-48]",
            "ldur q5, [x5, #-32]",
            "sha1su0 v3.4s, v4.4s, v5.4s",
            "ldur q4, [x5, #-16]",
            "sha1su1 v3.4s, v4.4s",
            "str q3, [x5]",
            "add x4, x4, #16",
            "cmp x4, #320",
            "b.ne 3b",
            "ldr q0, [{state}]",
            "rev32 v0.16b, v0.16b",
            "ldr s1, [{state}, #16]",
            "rev32 v1.16b, v1.16b",
            "mov x4, #0",
            "mov w6, #31129",
            "movk w6, #23170, lsl #16",
            "dup v5.4s, w6",
            "4:",
            "add x5, {schedule}, x4",
            "ldr q3, [x5]",
            "add v3.4s, v3.4s, v5.4s",
            "sha1h s2, s0",
            "sha1c q0, s1, v3.4s",
            "mov v1.16b, v2.16b",
            "add x4, x4, #16",
            "cmp x4, #80",
            "b.ne 4b",
            "mov w6, #60321",
            "movk w6, #28377, lsl #16",
            "dup v5.4s, w6",
            "5:",
            "add x5, {schedule}, x4",
            "ldr q3, [x5]",
            "add v3.4s, v3.4s, v5.4s",
            "sha1h s2, s0",
            "sha1p q0, s1, v3.4s",
            "mov v1.16b, v2.16b",
            "add x4, x4, #16",
            "cmp x4, #160",
            "b.ne 5b",
            "mov w6, #48348",
            "movk w6, #36635, lsl #16",
            "dup v5.4s, w6",
            "6:",
            "add x5, {schedule}, x4",
            "ldr q3, [x5]",
            "add v3.4s, v3.4s, v5.4s",
            "sha1h s2, s0",
            "sha1m q0, s1, v3.4s",
            "mov v1.16b, v2.16b",
            "add x4, x4, #16",
            "cmp x4, #240",
            "b.ne 6b",
            "mov w6, #49622",
            "movk w6, #51810, lsl #16",
            "dup v5.4s, w6",
            "7:",
            "add x5, {schedule}, x4",
            "ldr q3, [x5]",
            "add v3.4s, v3.4s, v5.4s",
            "sha1h s2, s0",
            "sha1p q0, s1, v3.4s",
            "mov v1.16b, v2.16b",
            "add x4, x4, #16",
            "cmp x4, #320",
            "b.ne 7b",
            "ldr q3, [{state}]",
            "rev32 v3.16b, v3.16b",
            "add v0.4s, v0.4s, v3.4s",
            "rev32 v0.16b, v0.16b",
            "str q0, [{state}]",
            "ldr s4, [{state}, #16]",
            "rev32 v4.16b, v4.16b",
            "add v1.4s, v1.4s, v4.4s",
            "rev32 v1.16b, v1.16b",
            "str s1, [{state}, #16]",
            "movi v0.16b, #0",
            "mov x4, #0",
            "8:",
            "add x5, {schedule}, x4",
            "str q0, [x5]",
            "add x4, x4, #16",
            "cmp x4, #320",
            "b.ne 8b",
            "// BRYNJA_REGISTER_ERASE",
            "mov x4, xzr",
            "mov x5, xzr",
            "mov x6, xzr",
            "movi v0.16b, #0",
            "movi v1.16b, #0",
            "movi v2.16b, #0",
            "movi v3.16b, #0",
            "movi v4.16b, #0",
            "movi v5.16b, #0",
            "cmp xzr, xzr",
            "// BRYNJA_SECRET_END",
            state = in(reg) state.as_mut_ptr(),
            block = in(reg) block.as_ptr(),
            schedule = in(reg) schedule.as_mut_ptr(),
            out("x4") _,
            out("x5") _,
            out("x6") _,
            out("v0") _,
            out("v1") _,
            out("v2") _,
            out("v3") _,
            out("v4") _,
            out("v5") _,
            options(nostack),
        );
    }
}
