//! Opaque eight-lane AVX2 MD5 compression; MD5 remains collision-broken.
#![allow(unsafe_code)]

/// Retains packed output only; erases non-output scratch and working registers.
/// Caller packing, output handling and asynchronous interruption are separate.
///
/// # Safety
/// AVX2 and OS-enabled YMM state must hold on every eligible CPU during this call.
#[target_feature(enable = "avx2")]
#[inline(never)]
pub unsafe extern "C" fn compress(scratch: &mut [u8; 864], constants: &[u32; 80]) {
    // SAFETY: Exact byte regions are initial 0..128, words 128..640, output
    // 640..768 and temporary 768..864. Public counters bound all 64 rounds,
    // message indices 0..16 and shift indices 0..16. Constants are read-only;
    // all scratch accesses are byte-aligned. Only independent packed outputs
    // survive; inactive Arm output halves are zeroed. Computation, scratch
    // erasure and RAX/RCX/RDX, YMM0..3 erasure stay inside one side-effecting
    // block with no calls, stack accesses or secret Rust outputs. Early clobbers
    // exclude both pointers; flags are erased on normal return.
    unsafe {
        core::arch::asm!(
            "# BRYNJA_SECRET_BEGIN",
            "xor ecx, ecx",
            "2:",
            "vmovdqu ymm0, [{scratch} + rcx]",
            "vmovdqu [{scratch} + rcx + 640], ymm0",
            "add rcx, 32",
            "cmp rcx, 128",
            "jne 2b",
            "xor ecx, ecx",
            "3:",
            "vmovdqu ymm0, [{scratch} + 672]",
            "vmovdqu ymm1, [{scratch} + 704]",
            "vmovdqu ymm2, [{scratch} + 736]",
            "cmp ecx, 16",
            "jb 4f",
            "cmp ecx, 32",
            "jb 5f",
            "cmp ecx, 48",
            "jb 6f",
            "vpcmpeqd ymm3, ymm3, ymm3",
            "vpxor ymm2, ymm2, ymm3",
            "vpor ymm0, ymm0, ymm2",
            "vpxor ymm0, ymm0, ymm1",
            "imul edx, ecx, 7",
            "jmp 7f",
            "4:",
            "vpxor ymm1, ymm1, ymm2",
            "vpand ymm0, ymm0, ymm1",
            "vpxor ymm0, ymm0, ymm2",
            "mov edx, ecx",
            "jmp 7f",
            "5:",
            "vpxor ymm0, ymm0, ymm1",
            "vpand ymm0, ymm0, ymm2",
            "vpxor ymm0, ymm0, ymm1",
            "imul edx, ecx, 5",
            "add edx, 1",
            "jmp 7f",
            "6:",
            "vpxor ymm0, ymm0, ymm1",
            "vpxor ymm0, ymm0, ymm2",
            "imul edx, ecx, 3",
            "add edx, 5",
            "7:",
            "and edx, 15",
            "shl edx, 5",
            "vpaddd ymm0, ymm0, [{scratch} + rdx + 128]",
            "vpaddd ymm0, ymm0, [{scratch} + 640]",
            "vpbroadcastd ymm1, [{constants} + rcx*4]",
            "vpaddd ymm0, ymm0, ymm1",
            "mov eax, ecx",
            "shr eax, 2",
            "and eax, 12",
            "mov edx, ecx",
            "and edx, 3",
            "or eax, edx",
            "mov eax, [{constants} + rax*4 + 256]",
            "vmovd xmm1, eax",
            "vpslld ymm2, ymm0, xmm1",
            "neg eax",
            "add eax, 32",
            "vmovd xmm1, eax",
            "vpsrld ymm0, ymm0, xmm1",
            "vpor ymm2, ymm2, ymm0",
            "vpaddd ymm2, ymm2, [{scratch} + 672]",
            "vmovdqu ymm0, [{scratch} + 736]",
            "vmovdqu [{scratch} + 640], ymm0",
            "vmovdqu ymm0, [{scratch} + 704]",
            "vmovdqu [{scratch} + 736], ymm0",
            "vmovdqu ymm0, [{scratch} + 672]",
            "vmovdqu [{scratch} + 704], ymm0",
            "vmovdqu [{scratch} + 672], ymm2",
            "inc ecx",
            "cmp ecx, 64",
            "jne 3b",
            "xor ecx, ecx",
            "8:",
            "vmovdqu ymm0, [{scratch} + rcx + 640]",
            "vpaddd ymm0, ymm0, [{scratch} + rcx]",
            "vmovdqu [{scratch} + rcx + 640], ymm0",
            "add rcx, 32",
            "cmp rcx, 128",
            "jne 8b",
            "vpxor ymm0, ymm0, ymm0",
            "xor ecx, ecx",
            "9:",
            "vmovdqu [{scratch} + rcx], ymm0",
            "add rcx, 32",
            "cmp rcx, 640",
            "jne 9b",
            "vmovdqu [{scratch} + 768], ymm0",
            "vmovdqu [{scratch} + 800], ymm0",
            "vmovdqu [{scratch} + 832], ymm0",
            "# BRYNJA_REGISTER_ERASE",
            "xor eax, eax",
            "xor ecx, ecx",
            "xor edx, edx",
            "vpxor ymm0, ymm0, ymm0",
            "vpxor ymm1, ymm1, ymm1",
            "vpxor ymm2, ymm2, ymm2",
            "vpxor ymm3, ymm3, ymm3",
            "cmp eax, eax",
            // Clear the AVX upper-state tracker after all secret working wipes.
            "vzeroupper",
            "# BRYNJA_SECRET_END",
            scratch = in(reg) scratch.as_mut_ptr(),
            constants = in(reg) constants.as_ptr(),
            out("rax") _,
            out("rcx") _,
            out("rdx") _,
            out("ymm0") _,
            out("ymm1") _,
            out("ymm2") _,
            out("ymm3") _,
            // VZEROUPPER also writes upper halves of otherwise unused registers.
            // Declare all aliases; the compiler preserves Win64's low XMM6-15.
            out("ymm4") _, out("ymm5") _, out("ymm6") _, out("ymm7") _,
            out("ymm8") _, out("ymm9") _, out("ymm10") _, out("ymm11") _,
            out("ymm12") _, out("ymm13") _, out("ymm14") _, out("ymm15") _,
            options(nostack),
        );
    }
}
