[workspace]
members = ["crates/*"]
default-members = ["crates/brynja"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.90"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/valkyoth/brynja"
repository = "https://github.com/valkyoth/brynja"

[workspace.lints.rust]
unsafe_code = "deny"
unsafe_op_in_unsafe_fn = "forbid"
unused_must_use = "deny"
missing_docs = "deny"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }

[workspace.lints.clippy]
panic = "forbid"
unwrap_used = "forbid"
expect_used = "forbid"
undocumented_unsafe_blocks = "forbid"
indexing_slicing = "forbid"
arithmetic_side_effects = "forbid"
cast_possible_truncation = "forbid"
cast_sign_loss = "forbid"
too_many_arguments = "forbid"

[profile.release]
overflow-checks = true
panic = "abort"
codegen-units = 1
lto = "fat"

[workspace.dependencies]
brynja-core = { path = "crates/brynja-core", version = "=0.9.0" }
brynja-crypto = { path = "crates/brynja-crypto", version = "=0.1.2" }
brynja-hash-core = { path = "crates/brynja-hash-core", version = "=0.1.0" }
brynja-hash-sha2 = { path = "crates/brynja-hash-sha2", version = "=0.1.0" }
brynja-crypto-cpu = { path = "crates/brynja-crypto-cpu", version = "=0.1.1" }
brynja-crypto-cpu-std = { path = "crates/brynja-crypto-cpu-std", version = "=0.1.1" }
brynja-pki = { path = "crates/brynja-pki", version = "=0.2.0" }
brynja-protocol = { path = "crates/brynja-protocol", version = "=0.1.0" }
brynja-tls = { path = "crates/brynja-tls", version = "=0.1.8" }
brynja-tls12 = { path = "crates/brynja-tls12", version = "=0.1.8" }
brynja-tls13 = { path = "crates/brynja-tls13", version = "=0.1.8" }
brynja-tls13-handshake = { path = "crates/brynja-tls13-handshake", version = "=0.1.8" }
brynja-dtls = { path = "crates/brynja-dtls", version = "=0.1.8" }
brynja-platform = { path = "crates/brynja-platform", version = "=0.1.8" }
brynja-quic-tls = { path = "crates/brynja-quic-tls", version = "=0.1.8" }
brynja-sanitization = { path = "crates/brynja-sanitization", version = "=0.1.1" }
brynja-legacy-pct = { path = "crates/brynja-legacy-pct", version = "=0.1.0" }
brynja-legacy-snp = { path = "crates/brynja-legacy-snp", version = "=0.1.0" }
brynja-legacy-ssl2 = { path = "crates/brynja-legacy-ssl2", version = "=0.1.0" }
brynja-legacy-ssl3 = { path = "crates/brynja-legacy-ssl3", version = "=0.1.0" }
brynja-legacy-tls10 = { path = "crates/brynja-legacy-tls10", version = "=0.1.0" }
brynja-legacy-tls11 = { path = "crates/brynja-legacy-tls11", version = "=0.1.0" }
brynja-legacy-wtls = { path = "crates/brynja-legacy-wtls", version = "=0.1.0" }
sanitization = { version = "=2.0.3", default-features = false }
