[package]
name = "brynja-quic-tls"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"
description = "QUIC TLS handshake integration for Brynja"
publish = ["crates-io"]

[features]
default = []


[dependencies]
brynja-core = { workspace = true }
brynja-tls13-handshake = { workspace = true }

[lints]
workspace = true
