//! Eight independent SHA-256 lanes in one opaque AVX2 cleanup boundary.
#![allow(unsafe_code)]

/// Reads packed initial state and 16 message words; retains only work outputs.
/// All addresses use byte alignment; state/message words use native LE order.
///
/// # Safety
/// AVX2 and OS-enabled YMM state must hold on every eligible CPU during this call.
#[target_feature(enable = "avx2")]
#[inline(never)]
pub unsafe extern "C" fn compress(scratch: &mut [u8; 2752], constants: &[u32; 64]) {
    // SAFETY: Exact scratch regions are initial 0..256, schedule 256..2304,
    // work 2304..2560 and temporary 2560..2752. Public bounded loops expand
    // schedule offsets 768..2304 from already initialized preceding words,
    // execute 64 rounds and commit eight outputs without mixing SIMD lanes.
    // Everything secret stays in one opaque side-effecting block without stack
    // accesses or calls. All non-output scratch, RAX/RCX/RDX, YMM0..3 and flags
    // are erased before exit. Early clobbers exclude both live input pointers.
    unsafe {
        core::arch::asm!(
            "# BRYNJA_SECRET_BEGIN",
            "xor ecx, ecx",
            "2:",
            "vmovdqu ymm0, [{scratch} + rcx]",
            "vmovdqu [{scratch} + rcx + 2304], ymm0",
            "add rcx, 32",
            "cmp rcx, 256",
            "jne 2b",
            "mov ecx, 768",
            "3:",
            "vmovdqu ymm0, [{scratch} + rcx - 480]",
            "vpsrld ymm1, ymm0, 7",
            "vpslld ymm2, ymm0, 25",
            "vpor ymm1, ymm1, ymm2",
            "vpsrld ymm2, ymm0, 18",
            "vpslld ymm3, ymm0, 14",
            "vpor ymm2, ymm2, ymm3",
            "vpxor ymm1, ymm1, ymm2",
            "vpsrld ymm0, ymm0, 3",
            "vpxor ymm1, ymm1, ymm0",
            "vmovdqu [{scratch} + 2560], ymm1",
            "vmovdqu ymm0, [{scratch} + rcx - 64]",
            "vpsrld ymm1, ymm0, 17",
            "vpslld ymm2, ymm0, 15",
            "vpor ymm1, ymm1, ymm2",
            "vpsrld ymm2, ymm0, 19",
            "vpslld ymm3, ymm0, 13",
            "vpor ymm2, ymm2, ymm3",
            "vpxor ymm1, ymm1, ymm2",
            "vpsrld ymm0, ymm0, 10",
            "vpxor ymm1, ymm1, ymm0",
            "vpaddd ymm1, ymm1, [{scratch} + 2560]",
            "vpaddd ymm1, ymm1, [{scratch} + rcx - 512]",
            "vpaddd ymm1, ymm1, [{scratch} + rcx - 224]",
            "vmovdqu [{scratch} + rcx], ymm1",
            "add rcx, 32",
            "cmp rcx, 2304",
            "jne 3b",
            "xor ecx, ecx",
            "xor edx, edx",
            "4:",
            "vmovdqu ymm0, [{scratch} + 2304]",
            "vpsrld ymm1, ymm0, 2",
            "vpslld ymm2, ymm0, 30",
            "vpor ymm1, ymm1, ymm2",
            "vpsrld ymm2, ymm0, 13",
            "vpslld ymm3, ymm0, 19",
            "vpor ymm2, ymm2, ymm3",
            "vpxor ymm1, ymm1, ymm2",
            "vpsrld ymm2, ymm0, 22",
            "vpslld ymm3, ymm0, 10",
            "vpor ymm2, ymm2, ymm3",
            "vpxor ymm1, ymm1, ymm2",
            "vmovdqu [{scratch} + 2560], ymm1",
            "vmovdqu ymm0, [{scratch} + 2432]",
            "vpsrld ymm1, ymm0, 6",
            "vpslld ymm2, ymm0, 26",
            "vpor ymm1, ymm1, ymm2",
            "vpsrld ymm2, ymm0, 11",
            "vpslld ymm3, ymm0, 21",
            "vpor ymm2, ymm2, ymm3",
            "vpxor ymm1, ymm1, ymm2",
            "vpsrld ymm2, ymm0, 25",
            "vpslld ymm3, ymm0, 7",
            "vpor ymm2, ymm2, ymm3",
            "vpxor ymm1, ymm1, ymm2",
            "vmovdqu [{scratch} + 2592], ymm1",
            "vmovdqu ymm0, [{scratch} + 2432]",
            "vmovdqu ymm1, [{scratch} + 2464]",
            "vmovdqu ymm2, [{scratch} + 2496]",
            "vpxor ymm1, ymm1, ymm2",
            "vpand ymm0, ymm0, ymm1",
            "vpxor ymm0, ymm0, ymm2",
            "vmovdqu [{scratch} + 2624], ymm0",
            "vmovdqu ymm0, [{scratch} + 2304]",
            "vmovdqu ymm1, [{scratch} + 2336]",
            "vmovdqu ymm2, [{scratch} + 2368]",
            "vpand ymm3, ymm0, ymm1",
            "vpxor ymm0, ymm0, ymm1",
            "vpand ymm0, ymm0, ymm2",
            "vpxor ymm0, ymm0, ymm3",
            "vmovdqu [{scratch} + 2656], ymm0",
            "vmovdqu ymm0, [{scratch} + 2528]",
            "vpaddd ymm0, ymm0, [{scratch} + 2592]",
            "vpaddd ymm0, ymm0, [{scratch} + 2624]",
            "vpaddd ymm0, ymm0, [{scratch} + rcx + 256]",
            "vpbroadcastd ymm1, [{constants} + rdx]",
            "vpaddd ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 2688], ymm0",
            "vmovdqu ymm0, [{scratch} + 2560]",
            "vpaddd ymm0, ymm0, [{scratch} + 2656]",
            "vmovdqu [{scratch} + 2720], ymm0",
            "vmovdqu ymm0, [{scratch} + 2496]",
            "vmovdqu [{scratch} + 2528], ymm0",
            "vmovdqu ymm0, [{scratch} + 2464]",
            "vmovdqu [{scratch} + 2496], ymm0",
            "vmovdqu ymm0, [{scratch} + 2432]",
            "vmovdqu [{scratch} + 2464], ymm0",
            "vmovdqu ymm0, [{scratch} + 2400]",
            "vpaddd ymm0, ymm0, [{scratch} + 2688]",
            "vmovdqu [{scratch} + 2432], ymm0",
            "vmovdqu ymm0, [{scratch} + 2368]",
            "vmovdqu [{scratch} + 2400], ymm0",
            "vmovdqu ymm0, [{scratch} + 2336]",
            "vmovdqu [{scratch} + 2368], ymm0",
            "vmovdqu ymm0, [{scratch} + 2304]",
            "vmovdqu [{scratch} + 2336], ymm0",
            "vmovdqu ymm0, [{scratch} + 2688]",
            "vpaddd ymm0, ymm0, [{scratch} + 2720]",
            "vmovdqu [{scratch} + 2304], ymm0",
            "add rcx, 32",
            "add rdx, 4",
            "cmp rdx, 256",
            "jne 4b",
            "xor ecx, ecx",
            "5:",
            "vmovdqu ymm0, [{scratch} + rcx + 2304]",
            "vpaddd ymm0, ymm0, [{scratch} + rcx]",
            "vmovdqu [{scratch} + rcx + 2304], ymm0",
            "add rcx, 32",
            "cmp rcx, 256",
            "jne 5b",
            "xor eax, eax",
            "xor ecx, ecx",
            "6:",
            "mov [{scratch} + rcx], rax",
            "add rcx, 8",
            "cmp rcx, 2304",
            "jne 6b",
            "mov ecx, 2560",
            "7:",
            "mov [{scratch} + rcx], rax",
            "add rcx, 8",
            "cmp rcx, 2752",
            "jne 7b",
            "# BRYNJA_REGISTER_ERASE",
            "vpxor ymm0, ymm0, ymm0",
            "vpxor ymm1, ymm1, ymm1",
            "vpxor ymm2, ymm2, ymm2",
            "vpxor ymm3, ymm3, ymm3",
            "xor eax, eax",
            "xor ecx, ecx",
            "xor edx, edx",
            "cmp eax, eax",
            // Clear the AVX upper-state tracker after all secret working wipes.
            "vzeroupper",
            "# BRYNJA_SECRET_END",
            scratch = in(reg) scratch.as_mut_ptr(),
            constants = in(reg) constants.as_ptr(),
            out("rax") _, out("rcx") _, out("rdx") _,
            out("ymm0") _, out("ymm1") _, out("ymm2") _, out("ymm3") _,
            // VZEROUPPER also writes upper halves of otherwise unused registers.
            // Declare all aliases; the compiler preserves Win64's low XMM6-15.
            out("ymm4") _, out("ymm5") _, out("ymm6") _, out("ymm7") _,
            out("ymm8") _, out("ymm9") _, out("ymm10") _, out("ymm11") _,
            out("ymm12") _, out("ymm13") _, out("ymm14") _, out("ymm15") _,
            options(nostack),
        );
    }
}
