#!/usr/bin/env python3
"""Fail-closed policy for v0.24.11 combined modern-hash acceptance."""

from __future__ import annotations

import hashlib
import subprocess
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
FIXTURE = Path("assurance/hash-final-acceptance")
MANIFEST = FIXTURE / "Cargo.toml"
LOCK = FIXTURE / "Cargo.lock"
LIB = FIXTURE / "src/lib.rs"
MAIN = FIXTURE / "src/main.rs"
HASHES = Path("scripts/hash/final-acceptance-hashes.toml")
FILES = (
    MANIFEST,
    LOCK,
    LIB,
    MAIN,
    Path("assurance/sha2-public-api/src/lib.rs"),
    Path("assurance/sha3-public-api/src/lib.rs"),
    Path("assurance/sha3-hardened-api/src/lib.rs"),
    Path("scripts/sha2/check-sha2-public-api.py"),
    Path("scripts/sha2/check-sha2-hardened.py"),
    Path("scripts/sha3/check-sha3-public-api.py"),
    Path("scripts/sha3/check-sha3-hardened.py"),
    Path("scripts/sha2/check-sha2-bit-differential.py"),
    Path("scripts/sha3/check-sha3-bit-differential.py"),
    Path("scripts/sha2/check-sha2-hardened-codegen.sh"),
    Path("scripts/sha3/check-sha3-hardened-codegen.sh"),
    Path("scripts/checks.sh"),
    Path("scripts/ci/check-rust-version-matrix.sh"),
    Path("scripts/assurance/check-bare-metal.sh"),
    Path(".github/workflows/ci.yml"),
    Path("README.md"),
    Path("crates/brynja/README.md"),
    Path("crates/brynja-hash-sha2/README.md"),
    Path("crates/brynja-hash-sha3/README.md"),
    Path("docs/VERIFICATION_STATUS.md"),
    Path("docs/current-status.md"),
    Path("docs/RELEASE_PLAN.md"),
    Path("release-notes/RELEASE_NOTES_0.24.11.md"),
    Path("requirements/domains/cryptography.toml"),
    Path("standards/surface-policy.json"),
    Path("security/cryptographic-api-profile-policy.toml"),
    Path("crates/brynja-crypto-cpu/src/lib.rs"),
)


class FinalAcceptanceError(RuntimeError):
    """The combined hash closure differs from reviewed policy."""


def fail(message: str) -> None:
    raise FinalAcceptanceError(message)


def read(root: Path, relative: Path) -> str:
    path = root / relative
    if not path.is_file() or path.is_symlink():
        fail(f"combined acceptance input is not a regular file: {relative}")
    return path.read_text(encoding="utf-8")


def require(text: str, token: str, label: str) -> None:
    if token not in text:
        fail(f"{label} drift: {token}")


def expected_hashes(root: Path) -> dict[str, str]:
    document = tomllib.loads(read(root, HASHES))
    if set(document) != {"files"} or not isinstance(document["files"], dict):
        fail("combined acceptance hash inventory has invalid shape")
    return document["files"]


def write_hashes(root: Path) -> None:
    lines = ["# Generated by scripts/hash/check-final-acceptance.py --write.", "[files]"]
    for relative in FILES:
        digest = hashlib.sha256(read(root, relative).encode()).hexdigest()
        lines.append(f'"{relative.as_posix()}" = "{digest}"')
    (root / HASHES).write_text("\n".join(lines) + "\n", encoding="utf-8")


def validate(root: Path = ROOT, check_hashes: bool = True) -> None:
    loaded = {relative: read(root, relative) for relative in FILES}
    for relative in (LIB, MAIN):
        if len(loaded[relative].splitlines()) > 500:
            fail(f"combined acceptance source exceeds 500 lines: {relative}")
    manifest = tomllib.loads(loaded[MANIFEST])
    if manifest.get("package") != {
        "name": "brynja-hash-final-acceptance-fixture",
        "version": "0.0.0",
        "edition": "2024",
        "rust-version": "1.90",
        "publish": False,
    }:
        fail("combined acceptance package identity changed")
    dependencies = manifest.get("dependencies", {})
    if set(dependencies) != {
        "brynja-crypto-cpu", "brynja-hash-sha2", "brynja-hash-sha3",
        "brynja-sha2-public-api-fixture", "brynja-sha3-hardened-api-fixture",
        "brynja-sha3-public-api-fixture",
    }:
        fail("combined acceptance dependency closure changed")
    fixture = loaded[LIB]
    for token in (
        "#![no_std]", "brynja_sha2_public_api_fixture::run()",
        "brynja_sha3_public_api_fixture::run()",
        "brynja_sha3_hardened_api_fixture::exercise_all",
        "SHA2_HARDENED_STATE_IMPLEMENTED", "FIPS202_HARDENED_STATE_IMPLEMENTED",
        "IMPLEMENTED_BACKEND_COUNT == 7", "ADMITTED_BACKEND_COUNT == 0",
        "Sha256Backend::X86Sha", "Sha512Backend::Aarch64Sha512",
        "KeccakBackend::X86Avx2", "KeccakBackend::Aarch64Sha3",
    ):
        require(fixture, token, "combined downstream fixture")
    for forbidden in ("unsafe {", "std::", "alloc::", "for_candidate_evidence"):
        if forbidden in fixture:
            fail(f"combined fixture crossed forbidden boundary: {forbidden}")
    report = loaded[MAIN]
    for token in (
        "Combined SHA-2 and SHA-3/SHAKE final acceptance: PASS",
        "SHA-2: Fully implemented; independently verified: NO; FIPS validated: NO",
        "SHA-3/SHAKE: Fully implemented; independently verified: NO; FIPS validated: NO",
    ):
        require(report, token, "runnable final report")
    rows = (
        "| SHA-2 | ✅ Fully implemented | `brynja-hash-sha2` | ❌ Not independently verified |",
        "| SHA-3/SHAKE | ✅ Fully implemented | `brynja-hash-sha3` | ❌ Not independently verified |",
    )
    for relative in (Path("README.md"), Path("crates/brynja/README.md")):
        for row in rows:
            require(loaded[relative], row, "public family status")
    require(loaded[Path("docs/current-status.md")], "SHA-2 and SHA-3/SHAKE are Fully implemented", "current status")
    plan = loaded[Path("docs/RELEASE_PLAN.md")]
    require(
        plan,
        "### v0.24.11 - SHA-2 And SHA-3/SHAKE Cross-Backend Final Acceptance\n\n"
        "Status: awaiting green CI",
        "plan milestone and release status",
    )
    checks = loaded[Path("scripts/checks.sh")]
    for command in (
        "python3 scripts/hash/check-final-acceptance.py",
        "python3 scripts/hash/test-final-acceptance.py",
        "python3 scripts/sha2/check-sha2-public-api.py",
        "python3 scripts/sha3/check-sha3-public-api.py",
        "python3 scripts/sha2/check-sha2-hardened.py",
        "python3 scripts/sha3/check-sha3-hardened.py",
    ):
        require(checks, command, "repository evidence gate")
    matrix_counts = {
        Path("scripts/ci/check-rust-version-matrix.sh"): 1,
        Path("scripts/assurance/check-bare-metal.sh"): 1,
        Path(".github/workflows/ci.yml"): 2,
    }
    for relative, expected_count in matrix_counts.items():
        actual = loaded[relative].count("assurance/hash-final-acceptance/Cargo.toml")
        if actual != expected_count:
            fail(f"matrix acceptance count changed: {relative}: {actual}")
    exact_evidence_counts = {
        Path("standards/surface-policy.json"): ("scripts/hash/check-final-acceptance.py#main", 2),
        Path("requirements/domains/cryptography.toml"): ("scripts/hash/check-final-acceptance.py#main", 2),
        Path("security/cryptographic-api-profile-policy.toml"): ("scripts/hash/check-final-acceptance.py", 2),
    }
    for relative, (token, expected_count) in exact_evidence_counts.items():
        actual = loaded[relative].count(token)
        if actual != expected_count:
            fail(f"final evidence count changed: {relative}: {actual}")
    if check_hashes:
        expected = expected_hashes(root)
        if set(expected) != {path.as_posix() for path in FILES}:
            fail("combined acceptance reviewed hash inventory is incomplete")
        for relative, text in loaded.items():
            if hashlib.sha256(text.encode()).hexdigest() != expected[relative.as_posix()]:
                fail(f"combined acceptance reviewed hash drift: {relative}")


def run_fixture(root: Path = ROOT) -> str:
    result = subprocess.run(
        ["cargo", "run", "--quiet", "--locked", "--manifest-path", str(root / MANIFEST)],
        cwd=root,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        timeout=300,
    )
    if result.returncode != 0:
        fail(f"combined final fixture failed:\n{result.stdout}")
    return result.stdout
