//! Opaque legacy SHA-1 compression; SHA-1 remains collision-broken.
#![allow(unsafe_code)]

/// Compress one block; retain only chaining output and erase the schedule.
/// Caller buffers/copies, framing and asynchronous interruption are separate.
///
/// # Safety
/// The complete sha,sse2 bundle must remain available on every eligible CPU.
/// All three borrows must refer to distinct, initialized live regions.
#[target_feature(enable = "sha,sse2")]
#[inline(never)]
pub unsafe extern "C" fn compress(
    state: &mut [u8; 20],
    block: &[u8; 64],
    schedule: &mut [u8; 320],
) {
    // SAFETY: Exact byte arrays bound all unaligned accesses. State loads cover
    // 0..16 plus 16..20 only; block loads cover 0..64. Twenty 16-byte schedule
    // groups hold the four-word recurrence and all eighty rounds. Addresses and
    // branches depend only on fixed offsets or public counters. Endian conversion,
    // expansion, rounds and feed-forward stay inside one side-effecting block,
    // with no stack access, calls or Rust secret outputs. The entire schedule,
    // EAX and XMM0..3 and flags are erased before normal return. Early clobbers
    // exclude the pointers; ABI-preserved XMM6..15 are untouched.
    unsafe {
        core::arch::asm!(
            "# BRYNJA_SECRET_BEGIN",
            "mov eax, [{block} + 0]",
            "bswap eax",
            "mov [{schedule} + 12], eax",
            "mov eax, [{block} + 4]",
            "bswap eax",
            "mov [{schedule} + 8], eax",
            "mov eax, [{block} + 8]",
            "bswap eax",
            "mov [{schedule} + 4], eax",
            "mov eax, [{block} + 12]",
            "bswap eax",
            "mov [{schedule} + 0], eax",
            "mov eax, [{block} + 16]",
            "bswap eax",
            "mov [{schedule} + 28], eax",
            "mov eax, [{block} + 20]",
            "bswap eax",
            "mov [{schedule} + 24], eax",
            "mov eax, [{block} + 24]",
            "bswap eax",
            "mov [{schedule} + 20], eax",
            "mov eax, [{block} + 28]",
            "bswap eax",
            "mov [{schedule} + 16], eax",
            "mov eax, [{block} + 32]",
            "bswap eax",
            "mov [{schedule} + 44], eax",
            "mov eax, [{block} + 36]",
            "bswap eax",
            "mov [{schedule} + 40], eax",
            "mov eax, [{block} + 40]",
            "bswap eax",
            "mov [{schedule} + 36], eax",
            "mov eax, [{block} + 44]",
            "bswap eax",
            "mov [{schedule} + 32], eax",
            "mov eax, [{block} + 48]",
            "bswap eax",
            "mov [{schedule} + 60], eax",
            "mov eax, [{block} + 52]",
            "bswap eax",
            "mov [{schedule} + 56], eax",
            "mov eax, [{block} + 56]",
            "bswap eax",
            "mov [{schedule} + 52], eax",
            "mov eax, [{block} + 60]",
            "bswap eax",
            "mov [{schedule} + 48], eax",
            "movdqu xmm2, [{schedule} + 0]",
            "movdqu xmm3, [{schedule} + 16]",
            "sha1msg1 xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 32]",
            "pxor xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 48]",
            "sha1msg2 xmm2, xmm3",
            "movdqu [{schedule} + 64], xmm2",
            "movdqu xmm2, [{schedule} + 16]",
            "movdqu xmm3, [{schedule} + 32]",
            "sha1msg1 xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 48]",
            "pxor xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 64]",
            "sha1msg2 xmm2, xmm3",
            "movdqu [{schedule} + 80], xmm2",
            "movdqu xmm2, [{schedule} + 32]",
            "movdqu xmm3, [{schedule} + 48]",
            "sha1msg1 xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 64]",
            "pxor xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 80]",
            "sha1msg2 xmm2, xmm3",
            "movdqu [{schedule} + 96], xmm2",
            "movdqu xmm2, [{schedule} + 48]",
            "movdqu xmm3, [{schedule} + 64]",
            "sha1msg1 xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 80]",
            "pxor xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 96]",
            "sha1msg2 xmm2, xmm3",
            "movdqu [{schedule} + 112], xmm2",
            "movdqu xmm2, [{schedule} + 64]",
            "movdqu xmm3, [{schedule} + 80]",
            "sha1msg1 xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 96]",
            "pxor xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 112]",
            "sha1msg2 xmm2, xmm3",
            "movdqu [{schedule} + 128], xmm2",
            "movdqu xmm2, [{schedule} + 80]",
            "movdqu xmm3, [{schedule} + 96]",
            "sha1msg1 xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 112]",
            "pxor xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 128]",
            "sha1msg2 xmm2, xmm3",
            "movdqu [{schedule} + 144], xmm2",
            "movdqu xmm2, [{schedule} + 96]",
            "movdqu xmm3, [{schedule} + 112]",
            "sha1msg1 xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 128]",
            "pxor xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 144]",
            "sha1msg2 xmm2, xmm3",
            "movdqu [{schedule} + 160], xmm2",
            "movdqu xmm2, [{schedule} + 112]",
            "movdqu xmm3, [{schedule} + 128]",
            "sha1msg1 xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 144]",
            "pxor xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 160]",
            "sha1msg2 xmm2, xmm3",
            "movdqu [{schedule} + 176], xmm2",
            "movdqu xmm2, [{schedule} + 128]",
            "movdqu xmm3, [{schedule} + 144]",
            "sha1msg1 xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 160]",
            "pxor xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 176]",
            "sha1msg2 xmm2, xmm3",
            "movdqu [{schedule} + 192], xmm2",
            "movdqu xmm2, [{schedule} + 144]",
            "movdqu xmm3, [{schedule} + 160]",
            "sha1msg1 xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 176]",
            "pxor xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 192]",
            "sha1msg2 xmm2, xmm3",
            "movdqu [{schedule} + 208], xmm2",
            "movdqu xmm2, [{schedule} + 160]",
            "movdqu xmm3, [{schedule} + 176]",
            "sha1msg1 xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 192]",
            "pxor xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 208]",
            "sha1msg2 xmm2, xmm3",
            "movdqu [{schedule} + 224], xmm2",
            "movdqu xmm2, [{schedule} + 176]",
            "movdqu xmm3, [{schedule} + 192]",
            "sha1msg1 xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 208]",
            "pxor xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 224]",
            "sha1msg2 xmm2, xmm3",
            "movdqu [{schedule} + 240], xmm2",
            "movdqu xmm2, [{schedule} + 192]",
            "movdqu xmm3, [{schedule} + 208]",
            "sha1msg1 xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 224]",
            "pxor xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 240]",
            "sha1msg2 xmm2, xmm3",
            "movdqu [{schedule} + 256], xmm2",
            "movdqu xmm2, [{schedule} + 208]",
            "movdqu xmm3, [{schedule} + 224]",
            "sha1msg1 xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 240]",
            "pxor xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 256]",
            "sha1msg2 xmm2, xmm3",
            "movdqu [{schedule} + 272], xmm2",
            "movdqu xmm2, [{schedule} + 224]",
            "movdqu xmm3, [{schedule} + 240]",
            "sha1msg1 xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 256]",
            "pxor xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 272]",
            "sha1msg2 xmm2, xmm3",
            "movdqu [{schedule} + 288], xmm2",
            "movdqu xmm2, [{schedule} + 240]",
            "movdqu xmm3, [{schedule} + 256]",
            "sha1msg1 xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 272]",
            "pxor xmm2, xmm3",
            "movdqu xmm3, [{schedule} + 288]",
            "sha1msg2 xmm2, xmm3",
            "movdqu [{schedule} + 304], xmm2",
            "movdqu xmm0, [{state}]",
            "movdqa xmm3, xmm0",
            "psrlw xmm3, 8",
            "psllw xmm0, 8",
            "por xmm0, xmm3",
            "pshuflw xmm0, xmm0, 0xb1",
            "pshufhw xmm0, xmm0, 0xb1",
            "pshufd xmm0, xmm0, 0x1b",
            "mov eax, [{state} + 16]",
            "bswap eax",
            "movd xmm1, eax",
            "pslldq xmm1, 12",
            "movdqu xmm2, [{schedule}]",
            "paddd xmm2, xmm1",
            "movdqa xmm1, xmm0",
            "sha1rnds4 xmm0, xmm2, 0",
            "movdqu xmm2, [{schedule} + 16]",
            "sha1nexte xmm1, xmm2",
            "movdqa xmm2, xmm0",
            "sha1rnds4 xmm0, xmm1, 0",
            "movdqa xmm1, xmm2",
            "movdqu xmm2, [{schedule} + 32]",
            "sha1nexte xmm1, xmm2",
            "movdqa xmm2, xmm0",
            "sha1rnds4 xmm0, xmm1, 0",
            "movdqa xmm1, xmm2",
            "movdqu xmm2, [{schedule} + 48]",
            "sha1nexte xmm1, xmm2",
            "movdqa xmm2, xmm0",
            "sha1rnds4 xmm0, xmm1, 0",
            "movdqa xmm1, xmm2",
            "movdqu xmm2, [{schedule} + 64]",
            "sha1nexte xmm1, xmm2",
            "movdqa xmm2, xmm0",
            "sha1rnds4 xmm0, xmm1, 0",
            "movdqa xmm1, xmm2",
            "movdqu xmm2, [{schedule} + 80]",
            "sha1nexte xmm1, xmm2",
            "movdqa xmm2, xmm0",
            "sha1rnds4 xmm0, xmm1, 1",
            "movdqa xmm1, xmm2",
            "movdqu xmm2, [{schedule} + 96]",
            "sha1nexte xmm1, xmm2",
            "movdqa xmm2, xmm0",
            "sha1rnds4 xmm0, xmm1, 1",
            "movdqa xmm1, xmm2",
            "movdqu xmm2, [{schedule} + 112]",
            "sha1nexte xmm1, xmm2",
            "movdqa xmm2, xmm0",
            "sha1rnds4 xmm0, xmm1, 1",
            "movdqa xmm1, xmm2",
            "movdqu xmm2, [{schedule} + 128]",
            "sha1nexte xmm1, xmm2",
            "movdqa xmm2, xmm0",
            "sha1rnds4 xmm0, xmm1, 1",
            "movdqa xmm1, xmm2",
            "movdqu xmm2, [{schedule} + 144]",
            "sha1nexte xmm1, xmm2",
            "movdqa xmm2, xmm0",
            "sha1rnds4 xmm0, xmm1, 1",
            "movdqa xmm1, xmm2",
            "movdqu xmm2, [{schedule} + 160]",
            "sha1nexte xmm1, xmm2",
            "movdqa xmm2, xmm0",
            "sha1rnds4 xmm0, xmm1, 2",
            "movdqa xmm1, xmm2",
            "movdqu xmm2, [{schedule} + 176]",
            "sha1nexte xmm1, xmm2",
            "movdqa xmm2, xmm0",
            "sha1rnds4 xmm0, xmm1, 2",
            "movdqa xmm1, xmm2",
            "movdqu xmm2, [{schedule} + 192]",
            "sha1nexte xmm1, xmm2",
            "movdqa xmm2, xmm0",
            "sha1rnds4 xmm0, xmm1, 2",
            "movdqa xmm1, xmm2",
            "movdqu xmm2, [{schedule} + 208]",
            "sha1nexte xmm1, xmm2",
            "movdqa xmm2, xmm0",
            "sha1rnds4 xmm0, xmm1, 2",
            "movdqa xmm1, xmm2",
            "movdqu xmm2, [{schedule} + 224]",
            "sha1nexte xmm1, xmm2",
            "movdqa xmm2, xmm0",
            "sha1rnds4 xmm0, xmm1, 2",
            "movdqa xmm1, xmm2",
            "movdqu xmm2, [{schedule} + 240]",
            "sha1nexte xmm1, xmm2",
            "movdqa xmm2, xmm0",
            "sha1rnds4 xmm0, xmm1, 3",
            "movdqa xmm1, xmm2",
            "movdqu xmm2, [{schedule} + 256]",
            "sha1nexte xmm1, xmm2",
            "movdqa xmm2, xmm0",
            "sha1rnds4 xmm0, xmm1, 3",
            "movdqa xmm1, xmm2",
            "movdqu xmm2, [{schedule} + 272]",
            "sha1nexte xmm1, xmm2",
            "movdqa xmm2, xmm0",
            "sha1rnds4 xmm0, xmm1, 3",
            "movdqa xmm1, xmm2",
            "movdqu xmm2, [{schedule} + 288]",
            "sha1nexte xmm1, xmm2",
            "movdqa xmm2, xmm0",
            "sha1rnds4 xmm0, xmm1, 3",
            "movdqa xmm1, xmm2",
            "movdqu xmm2, [{schedule} + 304]",
            "sha1nexte xmm1, xmm2",
            "movdqa xmm2, xmm0",
            "sha1rnds4 xmm0, xmm1, 3",
            "movdqa xmm1, xmm2",
            "pxor xmm2, xmm2",
            "sha1nexte xmm1, xmm2",
            "pshufd xmm1, xmm1, 0xff",
            "mov eax, [{state} + 16]",
            "bswap eax",
            "movd xmm2, eax",
            "paddd xmm1, xmm2",
            "movd eax, xmm1",
            "bswap eax",
            "mov [{state} + 16], eax",
            "movdqu xmm2, [{state}]",
            "movdqa xmm3, xmm2",
            "psrlw xmm3, 8",
            "psllw xmm2, 8",
            "por xmm2, xmm3",
            "pshuflw xmm2, xmm2, 0xb1",
            "pshufhw xmm2, xmm2, 0xb1",
            "pshufd xmm2, xmm2, 0x1b",
            "paddd xmm0, xmm2",
            "movdqa xmm3, xmm0",
            "psrlw xmm3, 8",
            "psllw xmm0, 8",
            "por xmm0, xmm3",
            "pshuflw xmm0, xmm0, 0xb1",
            "pshufhw xmm0, xmm0, 0xb1",
            "pshufd xmm0, xmm0, 0x1b",
            "movdqu [{state}], xmm0",
            "pxor xmm0, xmm0",
            "movdqu [{schedule} + 0], xmm0",
            "movdqu [{schedule} + 16], xmm0",
            "movdqu [{schedule} + 32], xmm0",
            "movdqu [{schedule} + 48], xmm0",
            "movdqu [{schedule} + 64], xmm0",
            "movdqu [{schedule} + 80], xmm0",
            "movdqu [{schedule} + 96], xmm0",
            "movdqu [{schedule} + 112], xmm0",
            "movdqu [{schedule} + 128], xmm0",
            "movdqu [{schedule} + 144], xmm0",
            "movdqu [{schedule} + 160], xmm0",
            "movdqu [{schedule} + 176], xmm0",
            "movdqu [{schedule} + 192], xmm0",
            "movdqu [{schedule} + 208], xmm0",
            "movdqu [{schedule} + 224], xmm0",
            "movdqu [{schedule} + 240], xmm0",
            "movdqu [{schedule} + 256], xmm0",
            "movdqu [{schedule} + 272], xmm0",
            "movdqu [{schedule} + 288], xmm0",
            "movdqu [{schedule} + 304], xmm0",
            "# BRYNJA_REGISTER_ERASE",
            "xor eax, eax",
            "pxor xmm0, xmm0",
            "pxor xmm1, xmm1",
            "pxor xmm2, xmm2",
            "pxor xmm3, xmm3",
            "cmp eax, eax",
            "# BRYNJA_SECRET_END",
            state = in(reg) state.as_mut_ptr(),
            block = in(reg) block.as_ptr(),
            schedule = in(reg) schedule.as_mut_ptr(),
            out("eax") _,
            out("xmm0") _,
            out("xmm1") _,
            out("xmm2") _,
            out("xmm3") _,
            options(nostack),
        );
    }
}
