//! Baseline hardened SHA-224/256 scalar rounds with owned working storage.
#![allow(unsafe_code)]

pub(super) fn compress(state: &mut [u8; 64], block: &[u8; 128], scratch: &mut [u8; 640]) {
    // SAFETY: Fixed disjoint live operands; the public FIPS round table is exact.
    unsafe { scalar(state, block, scratch, &crate::compress::ROUND_CONSTANTS) };
}

/// # Safety
/// All four fixed arrays must be live and disjoint. State/input byte arrays may
/// be unaligned; constants must be the FIPS 180-4 SHA-256 table. Baseline x86-64
/// or little-endian AArch64 only. State bytes 32..64 and block bytes 64..128
/// are untouched. Scratch holds 64 words and eight work words, then clears fully.
#[inline(never)]
pub(super) unsafe extern "C" fn scalar(
    state: &mut [u8; 64],
    block: &[u8; 128],
    scratch: &mut [u8; 640],
    constants: &[u32; 64],
) {
    #[cfg(target_arch = "x86_64")]
    // SAFETY: Public offsets bound input to 64 bytes, state to 32 bytes, schedule
    // to 256 bytes, work words to 256..288 and final erasure to exactly 640.
    // No stack/calls or secret operands cross the opaque boundary.
    unsafe {
        core::arch::asm!(
            "# BRYNJA_SCALAR_BEGIN",
            "xor r10d, r10d",
            "2:",
            "mov eax, [{block} + r10]",
            "bswap eax",
            "mov [{scratch} + r10], eax",
            "add r10d, 4",
            "cmp r10d, 64",
            "jne 2b",
            "3:",
            "mov ecx, [{scratch} + r10 - 8]",
            "mov edx, ecx",
            "mov r8d, ecx",
            "ror ecx, 17",
            "ror edx, 19",
            "shr r8d, 10",
            "xor ecx, edx",
            "xor ecx, r8d",
            "mov eax, ecx",
            "mov ecx, [{scratch} + r10 - 60]",
            "mov edx, ecx",
            "mov r8d, ecx",
            "ror ecx, 7",
            "ror edx, 18",
            "shr r8d, 3",
            "xor ecx, edx",
            "xor ecx, r8d",
            "add eax, ecx",
            "add eax, [{scratch} + r10 - 28]",
            "add eax, [{scratch} + r10 - 64]",
            "mov [{scratch} + r10], eax",
            "add r10d, 4",
            "cmp r10d, 256",
            "jne 3b",
            "xor r10d, r10d",
            "4:",
            "mov eax, [{state} + r10]",
            "bswap eax",
            "mov [{scratch} + r10 + 256], eax",
            "add r10d, 4",
            "cmp r10d, 32",
            "jne 4b",
            "xor r10d, r10d",
            "5:",
            "mov eax, [{scratch} + 272]",
            "mov ecx, eax",
            "mov edx, eax",
            "ror eax, 6",
            "ror ecx, 11",
            "ror edx, 25",
            "xor eax, ecx",
            "xor eax, edx",
            "mov ecx, [{scratch} + 276]",
            "xor ecx, [{scratch} + 280]",
            "and ecx, [{scratch} + 272]",
            "xor ecx, [{scratch} + 280]",
            "add eax, ecx",
            "add eax, [{scratch} + 284]",
            "add eax, [{constants} + r10]",
            "add eax, [{scratch} + r10]",
            "mov r8d, [{scratch} + 256]",
            "mov ecx, r8d",
            "mov edx, r8d",
            "ror r8d, 2",
            "ror ecx, 13",
            "ror edx, 22",
            "xor r8d, ecx",
            "xor r8d, edx",
            "mov ecx, [{scratch} + 256]",
            "mov edx, ecx",
            "and ecx, [{scratch} + 260]",
            "or edx, [{scratch} + 260]",
            "and edx, [{scratch} + 264]",
            "or ecx, edx",
            "add r8d, ecx",
            "add r8d, eax",
            "add eax, [{scratch} + 268]",
            "mov ecx, [{scratch} + 264]",
            "mov [{scratch} + 268], ecx",
            "mov ecx, [{scratch} + 260]",
            "mov [{scratch} + 264], ecx",
            "mov ecx, [{scratch} + 256]",
            "mov [{scratch} + 260], ecx",
            "mov ecx, [{scratch} + 280]",
            "mov [{scratch} + 284], ecx",
            "mov ecx, [{scratch} + 276]",
            "mov [{scratch} + 280], ecx",
            "mov ecx, [{scratch} + 272]",
            "mov [{scratch} + 276], ecx",
            "mov [{scratch} + 256], r8d",
            "mov [{scratch} + 272], eax",
            "add r10d, 4",
            "cmp r10d, 256",
            "jne 5b",
            "xor r10d, r10d",
            "6:",
            "mov eax, [{state} + r10]",
            "bswap eax",
            "add eax, [{scratch} + r10 + 256]",
            "bswap eax",
            "mov [{state} + r10], eax",
            "add r10d, 4",
            "cmp r10d, 32",
            "jne 6b",
            "xor r10d, r10d",
            "7:",
            "mov dword ptr [{scratch} + r10], 0",
            "add r10d, 4",
            "cmp r10d, 640",
            "jne 7b",
            "# BRYNJA_SCALAR_ERASE",
            "xor eax, eax",
            "xor ecx, ecx",
            "xor edx, edx",
            "xor r8d, r8d",
            "xor r10d, r10d",
            "# BRYNJA_SCALAR_END",
            state = in(reg) state.as_mut_ptr(), block = in(reg) block.as_ptr(),
            scratch = in(reg) scratch.as_mut_ptr(), constants = in(reg) constants.as_ptr(),
            out("rax") _, out("rcx") _, out("rdx") _, out("r8") _, out("r10") _,
            options(nostack),
        );
    }
    #[cfg(target_arch = "aarch64")]
    // SAFETY: Same public bounds; X10 is a scratch pointer, X9 a public offset.
    // Only X4-X10 are working registers; no stack, SIMD or reserved X18.
    unsafe {
        core::arch::asm!(
            "// BRYNJA_SCALAR_BEGIN",
            "mov x9, xzr",
            "2:",
            "ldr w4, [{block}, x9]",
            "rev w4, w4",
            "str w4, [{scratch}, x9]",
            "add x9, x9, #4",
            "cmp x9, #64",
            "b.ne 2b",
            "3:",
            "add x10, {scratch}, x9",
            "ldur w5, [x10, #-8]",
            "ror w4, w5, #17",
            "ror w6, w5, #19",
            "eor w4, w4, w6",
            "eor w4, w4, w5, lsr #10",
            "ldur w5, [x10, #-60]",
            "ror w6, w5, #7",
            "ror w7, w5, #18",
            "eor w6, w6, w7",
            "eor w6, w6, w5, lsr #3",
            "add w4, w4, w6",
            "ldur w5, [x10, #-28]",
            "add w4, w4, w5",
            "ldur w5, [x10, #-64]",
            "add w4, w4, w5",
            "str w4, [{scratch}, x9]",
            "add x9, x9, #4",
            "cmp x9, #256",
            "b.ne 3b",
            "mov x9, xzr",
            "add x10, {scratch}, #256",
            "4:",
            "ldr w4, [{state}, x9]",
            "rev w4, w4",
            "str w4, [x10, x9]",
            "add x9, x9, #4",
            "cmp x9, #32",
            "b.ne 4b",
            "mov x9, xzr",
            "5:",
            "ldr w5, [{scratch}, #272]",
            "ror w4, w5, #6",
            "ror w6, w5, #11",
            "eor w4, w4, w6",
            "ror w6, w5, #25",
            "eor w4, w4, w6",
            "ldr w6, [{scratch}, #276]",
            "ldr w7, [{scratch}, #280]",
            "eor w6, w6, w7",
            "and w6, w6, w5",
            "eor w6, w6, w7",
            "add w4, w4, w6",
            "ldr w5, [{scratch}, #284]",
            "add w4, w4, w5",
            "ldr w5, [{constants}, x9]",
            "add w4, w4, w5",
            "ldr w5, [{scratch}, x9]",
            "add w4, w4, w5",
            "ldr w5, [{scratch}, #256]",
            "ror w8, w5, #2",
            "ror w6, w5, #13",
            "eor w8, w8, w6",
            "ror w6, w5, #22",
            "eor w8, w8, w6",
            "ldr w6, [{scratch}, #260]",
            "and w7, w5, w6",
            "orr w5, w5, w6",
            "ldr w6, [{scratch}, #264]",
            "and w5, w5, w6",
            "orr w5, w5, w7",
            "add w8, w8, w5",
            "add w8, w8, w4",
            "ldr w5, [{scratch}, #268]",
            "add w4, w4, w5",
            "ldr w5, [{scratch}, #264]",
            "str w5, [{scratch}, #268]",
            "ldr w5, [{scratch}, #260]",
            "str w5, [{scratch}, #264]",
            "ldr w5, [{scratch}, #256]",
            "str w5, [{scratch}, #260]",
            "ldr w5, [{scratch}, #280]",
            "str w5, [{scratch}, #284]",
            "ldr w5, [{scratch}, #276]",
            "str w5, [{scratch}, #280]",
            "ldr w5, [{scratch}, #272]",
            "str w5, [{scratch}, #276]",
            "str w8, [{scratch}, #256]",
            "str w4, [{scratch}, #272]",
            "add x9, x9, #4",
            "cmp x9, #256",
            "b.ne 5b",
            "mov x9, xzr",
            "add x10, {scratch}, #256",
            "6:",
            "ldr w4, [{state}, x9]",
            "rev w4, w4",
            "ldr w5, [x10, x9]",
            "add w4, w4, w5",
            "rev w4, w4",
            "str w4, [{state}, x9]",
            "add x9, x9, #4",
            "cmp x9, #32",
            "b.ne 6b",
            "mov x9, xzr",
            "7:",
            "str wzr, [{scratch}, x9]",
            "add x9, x9, #4",
            "cmp x9, #640",
            "b.ne 7b",
            "// BRYNJA_SCALAR_ERASE",
            "mov x4, xzr",
            "mov x5, xzr",
            "mov x6, xzr",
            "mov x7, xzr",
            "mov x8, xzr",
            "mov x9, xzr",
            "mov x10, xzr",
            "cmp xzr, xzr",
            "// BRYNJA_SCALAR_END",
            state = in(reg) state.as_mut_ptr(), block = in(reg) block.as_ptr(),
            scratch = in(reg) scratch.as_mut_ptr(), constants = in(reg) constants.as_ptr(),
            out("x4") _, out("x5") _, out("x6") _, out("x7") _, out("x8") _,
            out("x9") _, out("x10") _,
            options(nostack),
        );
    }
}
