[package]
name = "brynja-hash-sha2"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"
description = "First-party no_std SHA-2 implementations for Brynja"
publish = ["crates-io"]

[features]
default = []
cpu = ["dep:brynja-crypto-cpu"]

[dependencies]
brynja-hash-core = { workspace = true }
brynja-crypto-cpu = { workspace = true, optional = true }

[lints]
workspace = true
