//! Single-state Keccak-f[1600] with an opaque AVX2 cleanup boundary.
#![allow(unsafe_code)]

/// Import and permute caller state; commit output, clear scratch and registers.
/// Caller state remains owned by the caller, not erased. Import/export is inside
/// this boundary; pre-existing caller registers and upstream copies are not.
///
/// # Safety
/// AVX2 and OS-enabled XMM/YMM state must hold on every eligible CPU for this call.
#[target_feature(enable = "avx2")]
#[inline(never)]
pub unsafe extern "C" fn permute(
    scratch: &mut [u8; 576],
    constants: &[u64; 24],
    state: &mut [u8; 200],
) {
    // SAFETY: The initialized exclusive scratch contains 25 LE lanes at 0..200,
    // five columns at 200..240, five deltas at 240..280 and 25 rearranged lanes
    // at 280..480. All rho/pi addresses below are fixed, and chi reads exactly
    // one five-lane row at a time. The public round offset visits 0..192 by 8.
    // The entire secret computation stays in one side-effecting, stack-free
    // block. Exactly 25 words move between the disjoint state and scratch;
    // output commits only after all rounds. It clears all 576 scratch bytes,
    // RAX/RCX/RDX/R8, YMM0..3 and flags before exit. Early clobbers cannot overlap
    // any of the three pointers. No Rust secret
    // value, call or compiler-generated intermediate crosses the boundary.
    unsafe {
        core::arch::asm!(
            "# BRYNJA_SECRET_BEGIN",
            "xor ecx, ecx",
            "6:",
            "mov rax, [{state} + rcx]",
            "mov [{scratch} + rcx], rax",
            "add rcx, 8",
            "cmp rcx, 200",
            "jne 6b",
            "xor r8d, r8d",
            "2:",
            "xor ecx, ecx",
            "3:",
            "mov rax, [{scratch} + rcx]",
            "xor rax, [{scratch} + rcx + 40]",
            "xor rax, [{scratch} + rcx + 80]",
            "xor rax, [{scratch} + rcx + 120]",
            "xor rax, [{scratch} + rcx + 160]",
            "mov [{scratch} + rcx + 200], rax",
            "add rcx, 8",
            "cmp rcx, 40",
            "jne 3b",
            // D[x] = C[x-1] XOR ROL(C[x+1], 1); then fixed rho/pi lanes.
            "mov rax, [{scratch} + 232]",
            "mov rdx, [{scratch} + 208]",
            "rol rdx, 1",
            "xor rax, rdx",
            "mov [{scratch} + 240], rax",
            "mov rax, [{scratch} + 200]",
            "mov rdx, [{scratch} + 216]",
            "rol rdx, 1",
            "xor rax, rdx",
            "mov [{scratch} + 248], rax",
            "mov rax, [{scratch} + 208]",
            "mov rdx, [{scratch} + 224]",
            "rol rdx, 1",
            "xor rax, rdx",
            "mov [{scratch} + 256], rax",
            "mov rax, [{scratch} + 216]",
            "mov rdx, [{scratch} + 232]",
            "rol rdx, 1",
            "xor rax, rdx",
            "mov [{scratch} + 264], rax",
            "mov rax, [{scratch} + 224]",
            "mov rdx, [{scratch} + 200]",
            "rol rdx, 1",
            "xor rax, rdx",
            "mov [{scratch} + 272], rax",
            "mov rax, [{scratch} + 0]",
            "xor rax, [{scratch} + 240]",
            "rol rax, 0",
            "mov [{scratch} + 280], rax",
            "mov rax, [{scratch} + 8]",
            "xor rax, [{scratch} + 248]",
            "rol rax, 1",
            "mov [{scratch} + 360], rax",
            "mov rax, [{scratch} + 16]",
            "xor rax, [{scratch} + 256]",
            "rol rax, 62",
            "mov [{scratch} + 440], rax",
            "mov rax, [{scratch} + 24]",
            "xor rax, [{scratch} + 264]",
            "rol rax, 28",
            "mov [{scratch} + 320], rax",
            "mov rax, [{scratch} + 32]",
            "xor rax, [{scratch} + 272]",
            "rol rax, 27",
            "mov [{scratch} + 400], rax",
            "mov rax, [{scratch} + 40]",
            "xor rax, [{scratch} + 240]",
            "rol rax, 36",
            "mov [{scratch} + 408], rax",
            "mov rax, [{scratch} + 48]",
            "xor rax, [{scratch} + 248]",
            "rol rax, 44",
            "mov [{scratch} + 288], rax",
            "mov rax, [{scratch} + 56]",
            "xor rax, [{scratch} + 256]",
            "rol rax, 6",
            "mov [{scratch} + 368], rax",
            "mov rax, [{scratch} + 64]",
            "xor rax, [{scratch} + 264]",
            "rol rax, 55",
            "mov [{scratch} + 448], rax",
            "mov rax, [{scratch} + 72]",
            "xor rax, [{scratch} + 272]",
            "rol rax, 20",
            "mov [{scratch} + 328], rax",
            "mov rax, [{scratch} + 80]",
            "xor rax, [{scratch} + 240]",
            "rol rax, 3",
            "mov [{scratch} + 336], rax",
            "mov rax, [{scratch} + 88]",
            "xor rax, [{scratch} + 248]",
            "rol rax, 10",
            "mov [{scratch} + 416], rax",
            "mov rax, [{scratch} + 96]",
            "xor rax, [{scratch} + 256]",
            "rol rax, 43",
            "mov [{scratch} + 296], rax",
            "mov rax, [{scratch} + 104]",
            "xor rax, [{scratch} + 264]",
            "rol rax, 25",
            "mov [{scratch} + 376], rax",
            "mov rax, [{scratch} + 112]",
            "xor rax, [{scratch} + 272]",
            "rol rax, 39",
            "mov [{scratch} + 456], rax",
            "mov rax, [{scratch} + 120]",
            "xor rax, [{scratch} + 240]",
            "rol rax, 41",
            "mov [{scratch} + 464], rax",
            "mov rax, [{scratch} + 128]",
            "xor rax, [{scratch} + 248]",
            "rol rax, 45",
            "mov [{scratch} + 344], rax",
            "mov rax, [{scratch} + 136]",
            "xor rax, [{scratch} + 256]",
            "rol rax, 15",
            "mov [{scratch} + 424], rax",
            "mov rax, [{scratch} + 144]",
            "xor rax, [{scratch} + 264]",
            "rol rax, 21",
            "mov [{scratch} + 304], rax",
            "mov rax, [{scratch} + 152]",
            "xor rax, [{scratch} + 272]",
            "rol rax, 8",
            "mov [{scratch} + 384], rax",
            "mov rax, [{scratch} + 160]",
            "xor rax, [{scratch} + 240]",
            "rol rax, 18",
            "mov [{scratch} + 392], rax",
            "mov rax, [{scratch} + 168]",
            "xor rax, [{scratch} + 248]",
            "rol rax, 2",
            "mov [{scratch} + 472], rax",
            "mov rax, [{scratch} + 176]",
            "xor rax, [{scratch} + 256]",
            "rol rax, 61",
            "mov [{scratch} + 352], rax",
            "mov rax, [{scratch} + 184]",
            "xor rax, [{scratch} + 264]",
            "rol rax, 56",
            "mov [{scratch} + 432], rax",
            "mov rax, [{scratch} + 192]",
            "xor rax, [{scratch} + 272]",
            "rol rax, 14",
            "mov [{scratch} + 312], rax",
            "xor ecx, ecx",
            "4:",
            "vmovdqu ymm0, [{scratch} + rcx + 280]",
            "vmovdqu ymm1, [{scratch} + rcx + 288]",
            // Next = B1,B2,B3,B4; rotate then replace last lane with B0.
            "vpermq ymm2, ymm1, 0x39",
            "vpbroadcastq ymm3, [{scratch} + rcx + 280]",
            "vpblendd ymm2, ymm2, ymm3, 0xc0",
            "vpandn ymm1, ymm1, ymm2",
            "vpxor ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + rcx], ymm0",
            "mov rax, [{scratch} + rcx + 280]",
            "not rax",
            "and rax, [{scratch} + rcx + 288]",
            "xor rax, [{scratch} + rcx + 312]",
            "mov [{scratch} + rcx + 32], rax",
            "add rcx, 40",
            "cmp rcx, 200",
            "jne 4b",
            "mov rax, [{constants} + r8]",
            "xor [{scratch}], rax",
            "add r8, 8",
            "cmp r8, 192",
            "jne 2b",
            "xor ecx, ecx",
            "7:",
            "mov rax, [{scratch} + rcx]",
            "mov [{state} + rcx], rax",
            "add rcx, 8",
            "cmp rcx, 200",
            "jne 7b",
            "xor eax, eax",
            "xor ecx, ecx",
            "5:",
            "mov [{scratch} + rcx], rax",
            "add rcx, 8",
            "cmp rcx, 576",
            "jne 5b",
            "# BRYNJA_REGISTER_ERASE",
            "vpxor ymm0, ymm0, ymm0", "vpxor ymm1, ymm1, ymm1",
            "vpxor ymm2, ymm2, ymm2", "vpxor ymm3, ymm3, ymm3",
            "xor eax, eax", "xor ecx, ecx", "xor edx, edx", "xor r8d, r8d",
            "cmp eax, eax",
            // Clear the AVX upper-state tracker after all secret working wipes.
            "vzeroupper",
            "# BRYNJA_SECRET_END",
            scratch = in(reg) scratch.as_mut_ptr(),
            constants = in(reg) constants.as_ptr(),
            state = in(reg) state.as_mut_ptr(),
            out("rax") _, out("rcx") _, out("rdx") _, out("r8") _,
            out("ymm0") _, out("ymm1") _, out("ymm2") _, out("ymm3") _,
            // VZEROUPPER also writes upper halves of otherwise unused registers.
            // Declare all aliases; the compiler preserves Win64's low XMM6-15.
            out("ymm4") _, out("ymm5") _, out("ymm6") _, out("ymm7") _,
            out("ymm8") _, out("ymm9") _, out("ymm10") _, out("ymm11") _,
            out("ymm12") _, out("ymm13") _, out("ymm14") _, out("ymm15") _,
            options(nostack),
        );
    }
}
