[package]
name = "brynja-core"
version = "0.6.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"
description = "Transactional no_std buffer foundations for Brynja"
publish = ["crates-io"]

[features]
default = []


[lints]
workspace = true
