"""Reviewed capability rows: changes require implementation and assurance review.

This is a static inventory, not regenerated by the validator from README claims.
Independent review/FIPS status must never be inferred from internal test results.
"""

ROWS = {
    "crates/brynja-crypto-cpu/README.md": [
        "| Static x86-64 SHA-256 and AVX2 Keccak execution | ✅ Opt-in | ❌ No |",
        "| Static AArch64 SHA-256, SHA-512 and SHA3 Keccak execution | ✅ Opt-in | ❌ No |",
        "| Low-level hosted-authority boundary | ✅ Platform proof required | ❌ No |",
        "| Hardened SHA-2 and Keccak sessions with clearing scratch | ✅ Opt-in | ❌ No |",
        "| RISC-V Zknh SHA-256/SHA-512 candidates | 🚧 QEMU/codegen only; unadmitted | ❌ No |"
    ],
    "crates/brynja-legacy-pct/README.md": [
        "| PCT controlled interoperability | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-platform/README.md": [
        "| Platform entropy, clocks and deployment adapters | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-pki/README.md": [
        "| Bounded, non-recursive DER framing reader | ✅ Implemented | ❌ No |",
        "| Admitted ASN.1 primitive and canonical container values | ✅ Implemented | ❌ No |",
        "| General DER encoding and schema-driven ASN.1 decoding | ❌ Not implemented | ❌ No |",
        "| X.509, certificate paths, revocation and signature verification | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-xtask/README.md": [
        "| Repository task-helper package | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-legacy-md5/README.md": [
        "| MD5 | ✅ Fully implemented | ❌ Not independently verified |"
    ],
    "crates/brynja-mac-kmac/README.md": [
        "| KMAC128/256 and KMACXOF128/256 | ✅ Fully implemented | ❌ No |",
        "| Byte/bit input, opaque tags and typed secret XOF output | ✅ Implemented | ❌ No |",
        "| Hardened accelerated execution | ✅ Opt-in, platform-limited | ❌ No |"
    ],
    "crates/brynja-tls13/README.md": [
        "| TLS 1.3 engine | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-legacy-md5-std/README.md": [
        "| MD5 | ✅ Fully implemented | ❌ Not independently verified |"
    ],
    "crates/brynja-tls13-handshake/README.md": [
        "| Shared TLS 1.3 handshake state machine | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-legacy/README.md": [
        "| Opt-in legacy-protocol facade | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-legacy-wtls/README.md": [
        "| WTLS controlled interoperability | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-tls12/README.md": [
        "| TLS 1.2 engine | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-legacy-tls11/README.md": [
        "| TLS 1.1 controlled interoperability | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-tls/README.md": [
        "| Modern TLS facade | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-hash-sha3/README.md": [
        "| SHA3-224/256/384/512 and SHAKE128/256 | ✅ Fully implemented | ❌ No |",
        "| Byte/bit input and arbitrary-bit SHAKE output | ✅ Fully implemented | ❌ No |",
        "| cSHAKE128/256 and SP 800-185 encodings | ✅ Fully implemented | ❌ No |",
        "| Hardened states and classified outputs | ✅ Implemented | ❌ No |",
        "| Ordinary and hardened accelerated execution | ✅ Opt-in, platform-limited | ❌ No |"
    ],
    "crates/brynja-legacy-tls10/README.md": [
        "| TLS 1.0 controlled interoperability | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-test-support/README.md": [
        "| RFC 9850 diagnostic key-log encoder | ✅ Test-only | ❌ No |",
        "| Deterministic fault-injecting random engine | ✅ Test-only | ❌ No |",
        "| Scripted wall and monotonic clocks | ✅ Test-only | ❌ No |",
        "| Production randomness, clocks or secure protocols | ❌ Not provided | Not applicable |"
    ],
    "crates/brynja-hash-sha2/README.md": [
        "| SHA-2 (all six identities, ordinary and hardened byte and arbitrary-bit APIs) | ✅ Fully implemented | ❌ Not independently verified |",
        "| General SHA-512/t, all 510 valid parameters | ✅ Fully implemented; opt-in | ❌ No |",
        "| Ordinary and hardened CPU execution | ✅ Opt-in, platform-limited | ❌ No |"
    ],
    "crates/brynja-legacy-ssl3/README.md": [
        "| SSL 3.0 controlled interoperability | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-sanitization/README.md": [
        "| Fixed-size secret ownership and explicit Brynja-region copies | ✅ Implemented | ❌ No |",
        "| TLS, hash/cipher algorithms or a FIPS module | Not provided | Not applicable |"
    ],
    "crates/brynja-hash-parallel/README.md": [
        "| All four portable ParallelHash/ParallelHashXOF identities | ✅ Fully implemented | ❌ No |",
        "| Byte/bit input, streaming, scheduled leaves and hardened secret output | ✅ Implemented | ❌ No |",
        "| Opt-in accelerated scheduling and streaming | 🚧 In progress: qualification pending | ❌ No |"
    ],
    "crates/brynja-legacy-ssl2/README.md": [
        "| SSL 2.0 controlled interoperability | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-research-ssl1/README.md": [
        "| SSL 1.0 provenance reconstruction | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-hash-parallel-std/README.md": [
        "| Bounded portable ParallelHash/ParallelHashXOF worker executor | ✅ Implemented | ❌ No |",
        "| Independently selected hardened root/worker acceleration | 🚧 In progress: qualification pending | ❌ No |"
    ],
    "crates/brynja-legacy-snp/README.md": [
        "| SNP controlled interoperability | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-quic-tls/README.md": [
        "| TLS handshake integration for QUIC | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-hash-core/README.md": [
        "| Incremental hash and XOF interfaces | ✅ Implemented | ❌ No |",
        "| Canonical borrowed MSB-first bit strings | ✅ Implemented | ❌ No |",
        "| Cryptographic algorithms | Not this crate's responsibility | Not applicable |"
    ],
    "crates/brynja-legacy-sha1/README.md": [
        "| SHA-1 | ✅ Fully implemented | ❌ Not independently verified |"
    ],
    "crates/brynja-crypto-cpu-std/README.md": [
        "| Historical SHA-2 host observation and portable fallback | ✅ Implemented; candidate routes unadmitted | ❌ No |",
        "| Explicit hosted raw execution | ✅ Opt-in, qualifying AArch64 only | ❌ No |",
        "| Ordinary SHA-3/SHAKE/cSHAKE sponge adapters | ✅ Opt-in, public data only | ❌ No |"
    ],
    "crates/brynja-protocol/README.md": [
        "| TLS 1.2/1.3 record-envelope parsing and encoding | ✅ Implemented | ❌ No |",
        "| DTLS 1.2/1.3 record-envelope parsing and encoding | ✅ Implemented | ❌ No |",
        "| Handshake, record encryption and authenticated connections | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-legacy-sha1-std/README.md": [
        "| SHA-1 | ✅ Fully implemented | ❌ Not independently verified |"
    ],
    "crates/brynja-dtls/README.md": [
        "| DTLS 1.2/1.3 engines | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-proofs/README.md": [
        "| Repository proof-harness package | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-crypto/README.md": [
        "| All six named SHA-2 and all six SHA-3/SHAKE functions | ✅ Fully implemented, reexported | ❌ No |",
        "| cSHAKE, KMAC/KMACXOF, TupleHash and ParallelHash families | ✅ Fully implemented, reexported | ❌ No |",
        "| AEAD, KDF, RSA, ECC and executable provider effects | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-core/README.md": [
        "| Checked counters, budgets, transactional cursors and typed workspaces | ✅ Implemented | ❌ No |",
        "| Owned secret regions and compiler-resistant clearing | ✅ Implemented | ❌ No |",
        "| Fixed-width constant-time equality, selection and swap | ✅ Implemented | ❌ No |",
        "| Provider, entropy, clock, pending-operation and security-outcome contracts | ✅ Implemented contracts | ❌ No |",
        "| Bounded observational security events | ✅ Implemented | ❌ No |",
        "| OS providers, DRBGs and executable FIPS module | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-interop/README.md": [
        "| Repository interoperability harness | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-hash-tuple/README.md": [
        "| TupleHash / TupleHashXOF, all four identities | ✅ Fully implemented | ❌ No |",
        "| Byte/bit tuples, streamed items and hardened outputs | ✅ Implemented | ❌ No |",
        "| Hardened accelerated execution | ✅ Opt-in, platform-limited | ❌ No |"
    ]
}
