"""Reviewed capability rows: changes require implementation and assurance review.

This is a static inventory, not regenerated by the validator from README claims.
Independent review/FIPS status must never be inferred from internal test results.
"""

ROWS = {
    "crates/brynja-crypto-cpu/README.md": [
        "| Hardened SHA-224/256 batch compression with clearing packed storage | 🚧 CPU foundation; qualification pending | ❌ No |",
        "| Hardened SHA-512-family batch compression with clearing packed storage | 🚧 CPU foundation; qualification pending | ❌ No |",
        "| Hardened independent-state Keccak AVX2 / NEON with clearing storage | 🚧 CPU foundation; qualification pending | ❌ No |",
        "| SHA-512-family four-lane AVX2 / two-lane NEON compression | 🚧 Implemented; qualification pending | ❌ No |",
        "| Keccak four-state AVX2 / two-state NEON permutation | 🚧 Implemented; qualification pending | ❌ No |",
        "| Independent-message SHA-224/256 AVX2 / NEON kernels | ✅ Opt-in, platform-limited | ❌ No |",
        "| Static x86-64 SHA-256 and AVX2 Keccak execution | ✅ Opt-in | ❌ No |",
        "| Dedicated x86 SHA-512 ordinary and hardened execution | 🚧 Implemented; emulated qualification only | ❌ No |",
        "| Static AArch64 SHA-256, SHA-512 and SHA3 Keccak execution | ✅ Opt-in | ❌ No |",
        "| Low-level hosted-authority boundary | ✅ Platform proof required | ❌ No |",
        "| Hardened SHA-2 and Keccak sessions with clearing scratch | ✅ Opt-in | ❌ No |",
        "| RISC-V Zknh SHA-256/SHA-512 candidates | 🚧 QEMU/codegen only; unadmitted | ❌ No |"
    ],
    "crates/brynja-legacy-pct/README.md": [
        "| PCT controlled interoperability | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-platform/README.md": [
        "| Platform entropy, clocks and deployment adapters | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-pki/README.md": [
        "| Bounded, non-recursive DER framing reader | ✅ Implemented | ❌ No |",
        "| Admitted ASN.1 primitive and canonical container values | ✅ Implemented | ❌ No |",
        "| General DER encoding and schema-driven ASN.1 decoding | ❌ Not implemented | ❌ No |",
        "| X.509, certificate paths, revocation and signature verification | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-xtask/README.md": [
        "| Repository task-helper package | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-legacy-md5/README.md": [
        "| MD5 | ✅ Fully implemented | ❌ Not independently verified |",
        "| Ordinary batch AVX2 / NEON execution | 🚧 In progress; native qualification pending | ❌ No |",
        "| Hardened batch AVX2 / NEON execution | 🚧 In progress; retest and native evidence pending | ❌ No |",
        "| Caller-owned portable scoped workspace | 🚧 Implemented; residue qualification pending | ❌ No |",
        "| Caller-owned scoped hardened AVX2 / NEON batches | 🚧 Implemented; residue qualification pending | ❌ No |"
    ],
    "crates/brynja-mac-kmac/README.md": [
        "| KMAC128/256 and KMACXOF128/256 | ✅ Fully implemented | ❌ No |",
        "| Byte/bit input, opaque tags and typed secret XOF output | ✅ Implemented | ❌ No |",
        "| Hardened accelerated execution | ✅ Opt-in, platform-limited | ❌ No |",
        "| Scoped KMAC/KMACXOF128/256 storage | ✅ Portable and opt-in accelerated workspaces/readers | ❌ No |"
    ],
    "crates/brynja-tls13/README.md": [
        "| TLS 1.3 engine | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-legacy-md5-std/README.md": [
        "| MD5 | ✅ Fully implemented | ❌ Not independently verified |",
        "| Ordinary hosted batch SIMD | 🚧 In progress; native qualification pending | ❌ No |",
        "| Hardened hosted batch SIMD | 🚧 In progress; retest and native evidence pending | ❌ No |",
        "| Opt-in protected scalar MD5 session | 🚧 Implemented; qualification pending | ❌ No |"
    ],
    "crates/brynja-tls13-handshake/README.md": [
        "| Shared TLS 1.3 handshake state machine | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-legacy/README.md": [
        "| Opt-in legacy-protocol facade | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-legacy-wtls/README.md": [
        "| WTLS controlled interoperability | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-tls12/README.md": [
        "| TLS 1.2 engine | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-legacy-tls11/README.md": [
        "| TLS 1.1 controlled interoperability | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-tls/README.md": [
        "| Modern TLS facade | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-hash-sha3/README.md": [
        "| SHA3-224/256/384/512 and SHAKE128/256 | ✅ Fully implemented | ❌ No |",
        "| Byte/bit input and arbitrary-bit SHAKE output | ✅ Fully implemented | ❌ No |",
        "| cSHAKE128/256 and SP 800-185 encodings | ✅ Fully implemented | ❌ No |",
        "| Hardened states and classified outputs | ✅ Implemented | ❌ No |",
        "| Scoped in-place hardened SHA-3/SHAKE/cSHAKE | Development; ownership checks implemented, residue qualification pending | ❌ No |",
        "| Scoped accelerated SHA-3/SHAKE/cSHAKE | Development; explicit static/hosted session, residue qualification pending | ❌ No |",
        "| Ordinary and hardened accelerated execution | ✅ Opt-in, platform-limited | ❌ No |",
        "| Hardened SHA-3/SHAKE/cSHAKE multibuffer owners | 🚧 Implemented; qualification pending | ❌ No |",
        "| Independent-message multibuffer SHA-3/SHAKE/cSHAKE | Development; native qualification pending | ❌ No |"
    ],
    "crates/brynja-legacy-tls10/README.md": [
        "| TLS 1.0 controlled interoperability | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-test-support/README.md": [
        "| RFC 9850 diagnostic key-log encoder | ✅ Test-only | ❌ No |",
        "| Deterministic fault-injecting random engine | ✅ Test-only | ❌ No |",
        "| Scripted wall and monotonic clocks | ✅ Test-only | ❌ No |",
        "| Production randomness, clocks or secure protocols | ❌ Not provided | Not applicable |"
    ],
    "crates/brynja-hash-sha2/README.md": [
        "| Hardened SHA-224/256 multibuffer owners and typed secret output | 🚧 Implemented; qualification pending | ❌ No |",
        "| Hardened SHA-512-family multibuffer owners with exact general-t identity | 🚧 Implemented; qualification pending | ❌ No |",
        "| Independent-message SHA-512-family AVX2 / NEON batching | 🚧 Implemented; qualification pending | ❌ No |",
        "| Independent-message SHA-224/256 AVX2 / NEON batching | ✅ Opt-in, platform-limited | ❌ No |",
        "| SHA-2 (all six identities, ordinary and hardened byte and arbitrary-bit APIs) | ✅ Fully implemented | ❌ Not independently verified |",
        "| Scoped in-place hardened states for six named identities and general SHA-512/t | Development; ownership checks implemented, residue qualification pending | ❌ No |",
        "| Scoped named/general-t SHA-2 with explicit portable/static/hosted execution | Development; opt-in, platform-limited; residue qualification pending | ❌ No |",
        "| General SHA-512/t, all 510 valid parameters | ✅ Fully implemented; opt-in | ❌ No |",
        "| Ordinary and hardened CPU execution | ✅ Opt-in, platform-limited | ❌ No |",
        "| Dedicated x86 SHA-512-family execution (`sha512,avx2,avx`) | 🚧 Implemented; SDE tested, qualification pending | ❌ No |"
    ],
    "crates/brynja-legacy-ssl3/README.md": [
        "| SSL 3.0 controlled interoperability | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-sanitization/README.md": [
        "| Fixed-size secret ownership and explicit Brynja-region copies | ✅ Implemented | ❌ No |",
        "| TLS, hash/cipher algorithms or a FIPS module | Not provided | Not applicable |"
    ],
    "crates/brynja-hash-parallel/README.md": [
        "| All four portable ParallelHash/ParallelHashXOF identities | ✅ Fully implemented | ❌ No |",
        "| Byte/bit input, streaming, scheduled leaves and hardened secret output | ✅ Implemented | ❌ No |",
        "| Caller-owned portable scoped fixed-output/XOF workspaces | 🚧 Implemented; complete residue qualification pending | ❌ No |",
        "| Portable scoped exact-plan collectors with fixed/XOF output | 🚧 Implemented; qualification pending | ❌ No |",
        "| Accelerated scoped exact-plan collectors and leaf workspaces | 🚧 Implemented; qualification pending | ❌ No |",
        "| Typed multibuffer jobs and clearing result handoff to scoped collectors | 🚧 Implemented; qualification pending | ❌ No |",
        "| Scoped accelerated fixed-output/XOF root/leaf workspaces | 🚧 Implemented; qualification pending | ❌ No |",
        "| Opt-in accelerated scheduling and streaming | 🚧 In progress: qualification pending | ❌ No |",
        "| Hardened scheduled/streaming leaf SIMD groups | 🚧 Implemented; qualification pending | ❌ No |"
    ],
    "crates/brynja-legacy-ssl2/README.md": [
        "| SSL 2.0 controlled interoperability | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-research-ssl1/README.md": [
        "| SSL 1.0 provenance reconstruction | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-hash-parallel-std/README.md": [
        "| Bounded portable ParallelHash/ParallelHashXOF worker executor | ✅ Implemented | ❌ No |",
        "| Scoped portable root with bounded borrowed-leaf thread handoff | 🚧 Implemented; qualification pending | ❌ No |",
        "| Scoped root/leaf storage with independently selected threaded acceleration | 🚧 Implemented; qualification pending | ❌ No |",
        "| Independently selected hardened root/worker acceleration | 🚧 In progress: qualification pending | ❌ No |",
        "| Hardened multibuffer worker groups with clearing result transport | 🚧 Implemented; qualification pending | ❌ No |",
        "| Scoped multibuffer workers with guarded parent slots and scoped root | 🚧 Implemented; qualification pending | ❌ No |",
        "| Strict protected scalar root, concurrent leaf stacks, CVs and output | 🚧 Implemented; qualification pending | ❌ No |"
    ],
    "crates/brynja-legacy-snp/README.md": [
        "| SNP controlled interoperability | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-quic-tls/README.md": [
        "| TLS handshake integration for QUIC | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-hash-core/README.md": [
        "| Incremental hash and XOF interfaces | ✅ Implemented | ❌ No |",
        "| Canonical borrowed MSB-first bit strings | ✅ Implemented | ❌ No |",
        "| Cryptographic algorithms | Not this crate's responsibility | Not applicable |"
    ],
    "crates/brynja-legacy-sha1/README.md": [
        "| SHA-1 | ✅ Fully implemented | ❌ Not independently verified |",
        "| Opt-in ordinary acceleration | ✅ Opt-in, platform-limited | ❌ Not independently verified |",
        "| Opt-in hardened acceleration | ✅ Opt-in, platform-limited | ❌ Not independently verified |",
        "| Caller-owned portable scoped workspace | 🚧 Implemented; residue qualification pending | ❌ Not independently verified |",
        "| Scoped hardened execution workspace | 🚧 Portable/SHA-NI/Arm routes; residue qualification pending | ❌ Not independently verified |"
    ],
    "crates/brynja-crypto-cpu-std/README.md": [
        "| Protected byte storage (Linux GNU x86-64/little-endian AArch64) | 🚧 Implemented; qualification pending; not strict execution | ❌ No |",
        "| Joined single/group protected execution stacks (same Linux GNU targets) | 🚧 Implemented; qualification pending; not strict hashing | ❌ No |",
        "| Protected scalar SHA-2 sessions (same Linux GNU targets) | 🚧 Six named identities and general SHA-512/t; qualification pending | ❌ No |",
        "| Protected compiled SHA-2 hardware sessions (same Linux GNU targets) | 🚧 Explicit static kernels; qualification pending | ❌ No |",
        "| Protected scalar SHA-3/SHAKE/cSHAKE sessions (same Linux GNU targets) | 🚧 Eight identities with exact-bit output; qualification pending | ❌ No |",
        "| Protected scalar KMAC/KMACXOF sessions (same Linux GNU targets) | 🚧 Four identities, protected verification; qualification pending | ❌ No |",
        "| Protected scalar TupleHash/TupleHashXOF sessions (same Linux GNU targets) | 🚧 Four identities, exact item completion; qualification pending | ❌ No |",
        "| Hosted independent-message SHA-512-family batching | 🚧 Implemented; qualification pending | ❌ No |",
        "| Distinct hardened SHA-2 and Keccak hosted batch owners | 🚧 Implemented; qualification pending | ❌ No |",
        "| Hosted independent-message SHA-3/SHAKE/cSHAKE batching | 🚧 Implemented; qualification pending | ❌ No |",
        "| Hosted independent-message SHA-224/256 batching | ✅ Opt-in, platform-limited | ❌ No |",
        "| Historical SHA-2 host observation and portable fallback | ✅ Implemented; candidate routes unadmitted | ❌ No |",
        "| Explicit hosted raw execution | ✅ Opt-in, qualifying AArch64 only | ❌ No |",
        "| Ordinary SHA-3/SHAKE/cSHAKE sponge adapters | ✅ Opt-in, public data only | ❌ No |"
    ],
    "crates/brynja-protocol/README.md": [
        "| TLS 1.2/1.3 record-envelope parsing and encoding | ✅ Implemented | ❌ No |",
        "| DTLS 1.2/1.3 record-envelope parsing and encoding | ✅ Implemented | ❌ No |",
        "| Handshake, record encryption and authenticated connections | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-legacy-sha1-std/README.md": [
        "| SHA-1 | ✅ Fully implemented | ❌ Not independently verified |",
        "| Opt-in hosted ordinary acceleration | ✅ Opt-in, platform-limited | ❌ Not independently verified |",
        "| Opt-in hosted hardened acceleration | ✅ Opt-in, platform-limited | ❌ Not independently verified |",
        "| Protected scalar SHA-1 sessions (Linux GNU x86-64/little-endian AArch64) | 🚧 Implemented; qualification pending | ❌ Not independently verified |"
    ],
    "crates/brynja-dtls/README.md": [
        "| DTLS 1.2/1.3 engines | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-proofs/README.md": [
        "| Repository proof-harness package | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-crypto/README.md": [
        "| All six named SHA-2 and all six SHA-3/SHAKE functions | ✅ Fully implemented, reexported | ❌ No |",
        "| cSHAKE, KMAC/KMACXOF, TupleHash and ParallelHash families | ✅ Fully implemented, reexported | ❌ No |",
        "| AEAD, KDF, RSA, ECC and executable provider effects | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-core/README.md": [
        "| Checked counters, budgets, transactional cursors and typed workspaces | ✅ Implemented | ❌ No |",
        "| Owned secret regions and compiler-resistant clearing | ✅ Implemented | ❌ No |",
        "| Checked borrowed secret-region copies | ✅ Implemented; caller cleanup required | ❌ No |",
        "| Fixed-width constant-time equality, selection and swap | ✅ Implemented | ❌ No |",
        "| Provider, entropy, clock, pending-operation and security-outcome contracts | ✅ Implemented contracts | ❌ No |",
        "| Bounded observational security events | ✅ Implemented | ❌ No |",
        "| OS providers, DRBGs and executable FIPS module | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-interop/README.md": [
        "| Repository interoperability harness | ❌ Not implemented | ❌ No |"
    ],
    "crates/brynja-hash-tuple/README.md": [
        "| TupleHash / TupleHashXOF, all four identities | ✅ Fully implemented | ❌ No |",
        "| Byte/bit tuples, streamed items and hardened outputs | ✅ Implemented | ❌ No |",
        "| Hardened accelerated execution | ✅ Opt-in, platform-limited | ❌ No |",
        "| Scoped fixed TupleHash128/256 workspaces and item writers | ✅ Portable | ❌ No |",
        "| Scoped TupleHashXOF128/256 workspaces and incremental readers | ✅ Portable and opt-in accelerated | ❌ No |",
        "| Scoped fixed TupleHash128/256 acceleration | ✅ Opt-in, platform-limited | ❌ No |"
    ]
}
