[package]
name = "brynja-tls"
version = "0.1.3"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"
description = "Evergreen modern TLS facade and one-pass version router for Brynja"
publish = ["crates-io"]

[features]
default = []


[dependencies]
brynja-core = { workspace = true }
brynja-tls12 = { workspace = true }
brynja-tls13 = { workspace = true }

[lints]
workspace = true
