//! Baseline hardened SHA-512-family scalar rounds and owned rolling schedule.
#![allow(unsafe_code)]

pub(super) fn compress(state: &mut [u8; 64], block: &[u8; 128], scratch: &mut [u8; 640]) {
    // SAFETY: Fixed disjoint live operands; the public FIPS round table is exact.
    unsafe { scalar(state, block, scratch, &crate::compress64::ROUND_CONSTANTS) };
}

/// # Safety
/// All fixed arrays must be live and disjoint. Byte operands may be unaligned;
/// constants must contain the FIPS 180-4 SHA-512 table. Baseline x86-64 or
/// little-endian AArch64 only. Scratch holds sixteen rolling schedule words
/// (0..128), eight working words (128..192), and is fully erased before return.
#[inline(never)]
pub(super) unsafe extern "C" fn scalar(
    state: &mut [u8; 64],
    block: &[u8; 128],
    scratch: &mut [u8; 640],
    constants: &[u64; 80],
) {
    #[cfg(target_arch = "x86_64")]
    // SAFETY: Input/state offsets are bounded to 128/64 bytes. Every ring offset
    // is masked to 127 and stays eight-byte aligned. Constants cover 80 rounds.
    // All secret operations and the full 640-byte wipe stay stack/call-free.
    unsafe {
        core::arch::asm!(
            "# BRYNJA_SCALAR_BEGIN",
            "xor r10d, r10d",
            "2:",
            "mov rax, [{block} + r10]",
            "bswap rax",
            "mov [{scratch} + r10], rax",
            "add r10d, 8",
            "cmp r10d, 128",
            "jne 2b",
            "xor r10d, r10d",
            "3:",
            "mov rax, [{state} + r10]",
            "bswap rax",
            "mov [{scratch} + r10 + 128], rax",
            "add r10d, 8",
            "cmp r10d, 64",
            "jne 3b",
            "xor r10d, r10d",
            "4:",
            "mov r11d, r10d",
            "and r11d, 127",
            "cmp r10d, 128",
            "jb 5f",
            "lea r9d, [r11 + 112]",
            "and r9d, 127",
            "mov rcx, [{scratch} + r9]",
            "mov rdx, rcx",
            "mov r8, rcx",
            "ror rcx, 19",
            "ror rdx, 61",
            "shr r8, 6",
            "xor rcx, rdx",
            "xor rcx, r8",
            "mov rax, rcx",
            "lea r9d, [r11 + 8]",
            "and r9d, 127",
            "mov rcx, [{scratch} + r9]",
            "mov rdx, rcx",
            "mov r8, rcx",
            "ror rcx, 1",
            "ror rdx, 8",
            "shr r8, 7",
            "xor rcx, rdx",
            "xor rcx, r8",
            "add rax, rcx",
            "lea r9d, [r11 + 72]",
            "and r9d, 127",
            "add rax, [{scratch} + r9]",
            "add rax, [{scratch} + r11]",
            "mov [{scratch} + r11], rax",
            "5:",
            "mov rax, [{scratch} + 160]",
            "mov rcx, rax",
            "mov rdx, rax",
            "ror rax, 14",
            "ror rcx, 18",
            "ror rdx, 41",
            "xor rax, rcx",
            "xor rax, rdx",
            "mov rcx, [{scratch} + 168]",
            "xor rcx, [{scratch} + 176]",
            "and rcx, [{scratch} + 160]",
            "xor rcx, [{scratch} + 176]",
            "add rax, rcx",
            "add rax, [{scratch} + 184]",
            "add rax, [{constants} + r10]",
            "add rax, [{scratch} + r11]",
            "mov r8, [{scratch} + 128]",
            "mov rcx, r8",
            "mov rdx, r8",
            "ror r8, 28",
            "ror rcx, 34",
            "ror rdx, 39",
            "xor r8, rcx",
            "xor r8, rdx",
            "mov rcx, [{scratch} + 128]",
            "mov rdx, rcx",
            "and rcx, [{scratch} + 136]",
            "or rdx, [{scratch} + 136]",
            "and rdx, [{scratch} + 144]",
            "or rcx, rdx",
            "add r8, rcx",
            "add r8, rax",
            "add rax, [{scratch} + 152]",
            "mov rcx, [{scratch} + 144]",
            "mov [{scratch} + 152], rcx",
            "mov rcx, [{scratch} + 136]",
            "mov [{scratch} + 144], rcx",
            "mov rcx, [{scratch} + 128]",
            "mov [{scratch} + 136], rcx",
            "mov rcx, [{scratch} + 176]",
            "mov [{scratch} + 184], rcx",
            "mov rcx, [{scratch} + 168]",
            "mov [{scratch} + 176], rcx",
            "mov rcx, [{scratch} + 160]",
            "mov [{scratch} + 168], rcx",
            "mov [{scratch} + 128], r8",
            "mov [{scratch} + 160], rax",
            "add r10d, 8",
            "cmp r10d, 640",
            "jne 4b",
            "xor r10d, r10d",
            "6:",
            "mov rax, [{state} + r10]",
            "bswap rax",
            "add rax, [{scratch} + r10 + 128]",
            "bswap rax",
            "mov [{state} + r10], rax",
            "add r10d, 8",
            "cmp r10d, 64",
            "jne 6b",
            "xor r10d, r10d",
            "7:",
            "mov qword ptr [{scratch} + r10], 0",
            "add r10d, 8",
            "cmp r10d, 640",
            "jne 7b",
            "# BRYNJA_SCALAR_ERASE",
            "xor eax, eax",
            "xor ecx, ecx",
            "xor edx, edx",
            "xor r8d, r8d",
            "xor r9d, r9d",
            "xor r10d, r10d",
            "xor r11d, r11d",
            "# BRYNJA_SCALAR_END",
            state = in(reg) state.as_mut_ptr(), block = in(reg) block.as_ptr(),
            scratch = in(reg) scratch.as_mut_ptr(), constants = in(reg) constants.as_ptr(),
            out("rax") _, out("rcx") _, out("rdx") _, out("r8") _, out("r9") _, out("r10") _, out("r11") _,
            options(nostack),
        );
    }
    #[cfg(target_arch = "aarch64")]
    // SAFETY: Same fixed bounds and aligned ring indices. X9-X11 hold public
    // offsets/pointers; X4-X8 hold secret work. No stack, SIMD or reserved X18.
    unsafe {
        core::arch::asm!(
            "// BRYNJA_SCALAR_BEGIN",
            "mov x9, xzr",
            "2:",
            "ldr x4, [{block}, x9]",
            "rev x4, x4",
            "str x4, [{scratch}, x9]",
            "add x9, x9, #8",
            "cmp x9, #128",
            "b.ne 2b",
            "mov x9, xzr",
            "add x10, {scratch}, #128",
            "3:",
            "ldr x4, [{state}, x9]",
            "rev x4, x4",
            "str x4, [x10, x9]",
            "add x9, x9, #8",
            "cmp x9, #64",
            "b.ne 3b",
            "mov x9, xzr",
            "4:",
            "and x10, x9, #127",
            "cmp x9, #128",
            "b.lo 5f",
            "add x11, x10, #112",
            "and x11, x11, #127",
            "ldr x5, [{scratch}, x11]",
            "ror x4, x5, #19",
            "ror x6, x5, #61",
            "eor x4, x4, x6",
            "eor x4, x4, x5, lsr #6",
            "add x11, x10, #8",
            "and x11, x11, #127",
            "ldr x5, [{scratch}, x11]",
            "ror x6, x5, #1",
            "ror x7, x5, #8",
            "eor x6, x6, x7",
            "eor x6, x6, x5, lsr #7",
            "add x4, x4, x6",
            "add x11, x10, #72",
            "and x11, x11, #127",
            "ldr x5, [{scratch}, x11]",
            "add x4, x4, x5",
            "ldr x5, [{scratch}, x10]",
            "add x4, x4, x5",
            "str x4, [{scratch}, x10]",
            "5:",
            "ldr x5, [{scratch}, #160]",
            "ror x4, x5, #14",
            "ror x6, x5, #18",
            "eor x4, x4, x6",
            "ror x6, x5, #41",
            "eor x4, x4, x6",
            "ldr x6, [{scratch}, #168]",
            "ldr x7, [{scratch}, #176]",
            "eor x6, x6, x7",
            "and x6, x6, x5",
            "eor x6, x6, x7",
            "add x4, x4, x6",
            "ldr x5, [{scratch}, #184]",
            "add x4, x4, x5",
            "ldr x5, [{constants}, x9]",
            "add x4, x4, x5",
            "ldr x5, [{scratch}, x10]",
            "add x4, x4, x5",
            "ldr x5, [{scratch}, #128]",
            "ror x8, x5, #28",
            "ror x6, x5, #34",
            "eor x8, x8, x6",
            "ror x6, x5, #39",
            "eor x8, x8, x6",
            "ldr x6, [{scratch}, #136]",
            "and x7, x5, x6",
            "orr x5, x5, x6",
            "ldr x6, [{scratch}, #144]",
            "and x5, x5, x6",
            "orr x5, x5, x7",
            "add x8, x8, x5",
            "add x8, x8, x4",
            "ldr x5, [{scratch}, #152]",
            "add x4, x4, x5",
            "ldr x5, [{scratch}, #144]",
            "str x5, [{scratch}, #152]",
            "ldr x5, [{scratch}, #136]",
            "str x5, [{scratch}, #144]",
            "ldr x5, [{scratch}, #128]",
            "str x5, [{scratch}, #136]",
            "ldr x5, [{scratch}, #176]",
            "str x5, [{scratch}, #184]",
            "ldr x5, [{scratch}, #168]",
            "str x5, [{scratch}, #176]",
            "ldr x5, [{scratch}, #160]",
            "str x5, [{scratch}, #168]",
            "str x8, [{scratch}, #128]",
            "str x4, [{scratch}, #160]",
            "add x9, x9, #8",
            "cmp x9, #640",
            "b.ne 4b",
            "mov x9, xzr",
            "add x10, {scratch}, #128",
            "6:",
            "ldr x4, [{state}, x9]",
            "rev x4, x4",
            "ldr x5, [x10, x9]",
            "add x4, x4, x5",
            "rev x4, x4",
            "str x4, [{state}, x9]",
            "add x9, x9, #8",
            "cmp x9, #64",
            "b.ne 6b",
            "mov x9, xzr",
            "7:",
            "str xzr, [{scratch}, x9]",
            "add x9, x9, #8",
            "cmp x9, #640",
            "b.ne 7b",
            "// BRYNJA_SCALAR_ERASE",
            "mov x4, xzr",
            "mov x5, xzr",
            "mov x6, xzr",
            "mov x7, xzr",
            "mov x8, xzr",
            "mov x9, xzr",
            "mov x10, xzr",
            "mov x11, xzr",
            "cmp xzr, xzr",
            "// BRYNJA_SCALAR_END",
            state = in(reg) state.as_mut_ptr(), block = in(reg) block.as_ptr(),
            scratch = in(reg) scratch.as_mut_ptr(), constants = in(reg) constants.as_ptr(),
            out("x4") _, out("x5") _, out("x6") _, out("x7") _, out("x8") _,
            out("x9") _, out("x10") _, out("x11") _,
            options(nostack),
        );
    }
}
