//! Single-state Keccak-f[1600] with an opaque Arm SHA3 cleanup boundary.
#![allow(unsafe_code)]

/// Import and permute caller state; commit output, clear scratch and registers.
/// Caller state remains owned by the caller, not erased. Import/export is inside
/// this boundary; pre-existing caller registers and upstream copies are not.
///
/// # Safety
/// NEON/SHA3 must hold on every eligible CPU throughout this call.
#[target_feature(enable = "neon,sha3")]
#[inline(never)]
pub unsafe extern "C" fn permute(
    scratch: &mut [u8; 576],
    constants: &[u64; 24],
    state: &mut [u8; 200],
) {
    const {
        assert!(cfg!(target_endian = "little"));
    }
    // SAFETY: Scratch owns initialized lanes 0..200, columns 200..240, deltas
    // 240..280 and rearranged lanes 280..480. Fixed rho/pi offsets stay within
    // those regions. Each chi load fits its five-lane row; round offsets visit
    // 0..192 by eight. No stack access, call or Rust secret result escapes this
    // single side-effecting block. Exactly 25 words move between disjoint state
    // and scratch; output commits only after all rounds. It erases all 576 bytes, all working
    // X4/X5/X6/X7/X9 and V0..3, then NZCV. Early clobbers exclude input pointers;
    // preserved D8..15 are untouched. Normal unaligned memory is supported.
    unsafe {
        core::arch::asm!(
            "// BRYNJA_SECRET_BEGIN",
            "mov x7, #0",
            "6:",
            "ldr x5, [{state}, x7]",
            "str x5, [{scratch}, x7]",
            "add x7, x7, #8",
            "cmp x7, #200",
            "b.ne 6b",
            "mov x4, #0",
            "2:",
            "mov x7, #0",
            "3:",
            "add x9, {scratch}, x7",
            "ldr x5, [x9]",
            "ldr x6, [x9, #40]",
            "eor x5, x5, x6",
            "ldr x6, [x9, #80]",
            "eor x5, x5, x6",
            "ldr x6, [x9, #120]",
            "eor x5, x5, x6",
            "ldr x6, [x9, #160]",
            "eor x5, x5, x6",
            "str x5, [x9, #200]",
            "add x7, x7, #8",
            "cmp x7, #40",
            "b.ne 3b",
            "ldr x5, [{scratch}, #232]",
            "ldr x6, [{scratch}, #208]",
            "eor x5, x5, x6, ror #63",
            "str x5, [{scratch}, #240]",
            "ldr x5, [{scratch}, #200]",
            "ldr x6, [{scratch}, #216]",
            "eor x5, x5, x6, ror #63",
            "str x5, [{scratch}, #248]",
            "ldr x5, [{scratch}, #208]",
            "ldr x6, [{scratch}, #224]",
            "eor x5, x5, x6, ror #63",
            "str x5, [{scratch}, #256]",
            "ldr x5, [{scratch}, #216]",
            "ldr x6, [{scratch}, #232]",
            "eor x5, x5, x6, ror #63",
            "str x5, [{scratch}, #264]",
            "ldr x5, [{scratch}, #224]",
            "ldr x6, [{scratch}, #200]",
            "eor x5, x5, x6, ror #63",
            "str x5, [{scratch}, #272]",
            "ldr x5, [{scratch}, #0]",
            "ldr x6, [{scratch}, #240]",
            "eor x5, x5, x6",
            "ror x5, x5, #0",
            "str x5, [{scratch}, #280]",
            "ldr x5, [{scratch}, #8]",
            "ldr x6, [{scratch}, #248]",
            "eor x5, x5, x6",
            "ror x5, x5, #63",
            "str x5, [{scratch}, #360]",
            "ldr x5, [{scratch}, #16]",
            "ldr x6, [{scratch}, #256]",
            "eor x5, x5, x6",
            "ror x5, x5, #2",
            "str x5, [{scratch}, #440]",
            "ldr x5, [{scratch}, #24]",
            "ldr x6, [{scratch}, #264]",
            "eor x5, x5, x6",
            "ror x5, x5, #36",
            "str x5, [{scratch}, #320]",
            "ldr x5, [{scratch}, #32]",
            "ldr x6, [{scratch}, #272]",
            "eor x5, x5, x6",
            "ror x5, x5, #37",
            "str x5, [{scratch}, #400]",
            "ldr x5, [{scratch}, #40]",
            "ldr x6, [{scratch}, #240]",
            "eor x5, x5, x6",
            "ror x5, x5, #28",
            "str x5, [{scratch}, #408]",
            "ldr x5, [{scratch}, #48]",
            "ldr x6, [{scratch}, #248]",
            "eor x5, x5, x6",
            "ror x5, x5, #20",
            "str x5, [{scratch}, #288]",
            "ldr x5, [{scratch}, #56]",
            "ldr x6, [{scratch}, #256]",
            "eor x5, x5, x6",
            "ror x5, x5, #58",
            "str x5, [{scratch}, #368]",
            "ldr x5, [{scratch}, #64]",
            "ldr x6, [{scratch}, #264]",
            "eor x5, x5, x6",
            "ror x5, x5, #9",
            "str x5, [{scratch}, #448]",
            "ldr x5, [{scratch}, #72]",
            "ldr x6, [{scratch}, #272]",
            "eor x5, x5, x6",
            "ror x5, x5, #44",
            "str x5, [{scratch}, #328]",
            "ldr x5, [{scratch}, #80]",
            "ldr x6, [{scratch}, #240]",
            "eor x5, x5, x6",
            "ror x5, x5, #61",
            "str x5, [{scratch}, #336]",
            "ldr x5, [{scratch}, #88]",
            "ldr x6, [{scratch}, #248]",
            "eor x5, x5, x6",
            "ror x5, x5, #54",
            "str x5, [{scratch}, #416]",
            "ldr x5, [{scratch}, #96]",
            "ldr x6, [{scratch}, #256]",
            "eor x5, x5, x6",
            "ror x5, x5, #21",
            "str x5, [{scratch}, #296]",
            "ldr x5, [{scratch}, #104]",
            "ldr x6, [{scratch}, #264]",
            "eor x5, x5, x6",
            "ror x5, x5, #39",
            "str x5, [{scratch}, #376]",
            "ldr x5, [{scratch}, #112]",
            "ldr x6, [{scratch}, #272]",
            "eor x5, x5, x6",
            "ror x5, x5, #25",
            "str x5, [{scratch}, #456]",
            "ldr x5, [{scratch}, #120]",
            "ldr x6, [{scratch}, #240]",
            "eor x5, x5, x6",
            "ror x5, x5, #23",
            "str x5, [{scratch}, #464]",
            "ldr x5, [{scratch}, #128]",
            "ldr x6, [{scratch}, #248]",
            "eor x5, x5, x6",
            "ror x5, x5, #19",
            "str x5, [{scratch}, #344]",
            "ldr x5, [{scratch}, #136]",
            "ldr x6, [{scratch}, #256]",
            "eor x5, x5, x6",
            "ror x5, x5, #49",
            "str x5, [{scratch}, #424]",
            "ldr x5, [{scratch}, #144]",
            "ldr x6, [{scratch}, #264]",
            "eor x5, x5, x6",
            "ror x5, x5, #43",
            "str x5, [{scratch}, #304]",
            "ldr x5, [{scratch}, #152]",
            "ldr x6, [{scratch}, #272]",
            "eor x5, x5, x6",
            "ror x5, x5, #56",
            "str x5, [{scratch}, #384]",
            "ldr x5, [{scratch}, #160]",
            "ldr x6, [{scratch}, #240]",
            "eor x5, x5, x6",
            "ror x5, x5, #46",
            "str x5, [{scratch}, #392]",
            "ldr x5, [{scratch}, #168]",
            "ldr x6, [{scratch}, #248]",
            "eor x5, x5, x6",
            "ror x5, x5, #62",
            "str x5, [{scratch}, #472]",
            "ldr x5, [{scratch}, #176]",
            "ldr x6, [{scratch}, #256]",
            "eor x5, x5, x6",
            "ror x5, x5, #3",
            "str x5, [{scratch}, #352]",
            "ldr x5, [{scratch}, #184]",
            "ldr x6, [{scratch}, #264]",
            "eor x5, x5, x6",
            "ror x5, x5, #8",
            "str x5, [{scratch}, #432]",
            "ldr x5, [{scratch}, #192]",
            "ldr x6, [{scratch}, #272]",
            "eor x5, x5, x6",
            "ror x5, x5, #50",
            "str x5, [{scratch}, #312]",
            "mov x7, #0",
            "4:",
            "add x9, {scratch}, #280",
            "add x9, x9, x7",
            "ldr q0, [x9]",
            "ldur q1, [x9, #8]",
            "ldr q2, [x9, #16]",
            "bcax v0.16b, v0.16b, v2.16b, v1.16b",
            "str q0, [{scratch}, x7]",
            "ldr q0, [x9, #16]",
            "ldur q1, [x9, #24]",
            "ldr d2, [x9, #32]",
            "ldr d3, [x9]",
            "ins v2.d[1], v3.d[0]",
            "bcax v0.16b, v0.16b, v2.16b, v1.16b",
            "add x6, {scratch}, x7",
            "str q0, [x6, #16]",
            "ldr x5, [x9]",
            "mvn x5, x5",
            "ldr x9, [x9, #8]",
            "and x5, x5, x9",
            "ldr x9, [x6, #312]",
            "eor x5, x5, x9",
            "str x5, [x6, #32]",
            "add x7, x7, #40",
            "cmp x7, #200",
            "b.ne 4b",
            "ldr x5, [{constants}, x4]",
            "ldr x6, [{scratch}]",
            "eor x5, x5, x6",
            "str x5, [{scratch}]",
            "add x4, x4, #8",
            "cmp x4, #192",
            "b.ne 2b",
            "mov x7, #0",
            "7:",
            "ldr x5, [{scratch}, x7]",
            "str x5, [{state}, x7]",
            "add x7, x7, #8",
            "cmp x7, #200",
            "b.ne 7b",
            "mov x7, #0",
            "5:",
            "str xzr, [{scratch}, x7]",
            "add x7, x7, #8",
            "cmp x7, #576",
            "b.ne 5b",
            "// BRYNJA_REGISTER_ERASE",
            "movi v0.16b, #0", "movi v1.16b, #0",
            "movi v2.16b, #0", "movi v3.16b, #0",
            "mov x4, xzr", "mov x5, xzr", "mov x6, xzr",
            "mov x7, xzr", "mov x9, xzr",
            "cmp xzr, xzr",
            "// BRYNJA_SECRET_END",
            scratch = in(reg) scratch.as_mut_ptr(),
            constants = in(reg) constants.as_ptr(),
            state = in(reg) state.as_mut_ptr(),
            out("x4") _, out("x5") _, out("x6") _, out("x7") _, out("x9") _,
            out("v0") _, out("v1") _, out("v2") _, out("v3") _,
            options(nostack),
        );
    }
}
