#!/usr/bin/env python3
"""v0.24.17 hosted acceptance, frozen consumer contract and bounded execution."""

from __future__ import annotations

import hashlib
import os
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts/assurance"))
from assurance_process import run_bounded

FIXTURE = Path("assurance/sp800185-final")
FROZEN = Path("scripts/sp800185/frozen-portable-contract.toml")
HASHES = Path("scripts/sp800185/execution-acceptance-hashes.toml")
FILES = (
    *tuple(FIXTURE / name for name in (
        "Cargo.toml", "Cargo.lock", "src/lib.rs", "src/main.rs",
        "src/parallel.rs", "src/benchmark.rs",
    )),
    FROZEN,
    Path("scripts/sp800185/execution_acceptance.py"),
    Path("scripts/sp800185/check-execution-acceptance.py"),
    Path("scripts/sp800185/test-execution-acceptance.py"),
    Path("scripts/sp800185/capture-sp800185-native.py"),
    Path("scripts/sp800185/native_capture.py"),
    Path("scripts/checks.sh"),
    Path("scripts/ci/check-rust-version-matrix.sh"),
    Path(".github/workflows/ci.yml"),
    Path("docs/sp800185-final-acceptance.md"),
)
REPORT = (
    "SP 800-185 execution acceptance: PASS",
    "identities: 14", "parallel comparisons: 540", "bounded failure cases: 24",
    "unadmitted Keccak candidates: 2",
    "family closure: pending reviewed native evidence disposition",
    "independently verified: NO; FIPS 140-3 validated: NO",
)


class ExecutionError(RuntimeError):
    """Acceptance is incomplete, altered or unsuccessful."""


def read(root: Path, path: Path) -> str:
    candidate = root / path
    if candidate.is_symlink() or not candidate.is_file():
        raise ExecutionError(f"not a regular acceptance input: {path}")
    return candidate.read_text(encoding="utf-8")


def digest(text: str) -> str:
    # Normalize checkout CRLF through read_text, as for the other policies.
    return hashlib.sha256(text.encode()).hexdigest()


def write_hashes(root: Path = ROOT) -> None:
    lines = ["# Generated by check-execution-acceptance.py --write.", "[files]"]
    lines.extend(f'"{p.as_posix()}" = "{digest(read(root, p))}"' for p in FILES)
    (root / HASHES).write_text("\n".join(lines) + "\n", encoding="utf-8")


def validate(root: Path = ROOT, check_hashes: bool = True) -> None:
    sources = {path: read(root, path) for path in FILES}
    frozen = tomllib.loads(sources[FROZEN])
    expected = {
        *(f"assurance/sp800185-public-api/src/{name}.rs" for name in (
            "cshake", "facades", "kmac", "lib", "main", "parallelhash",
            "tuplehash", "vectors",
        )),
        "assurance/sp800185-public-api/fixtures/representative.txt",
    }
    if set(frozen) != {"baseline", "files"} or frozen["baseline"] != "v0.24.16":
        raise ExecutionError("frozen consumer baseline changed")
    if set(frozen["files"]) != expected:
        raise ExecutionError("frozen consumer inventory changed")
    for path, sha in frozen["files"].items():
        if digest(read(root, Path(path))) != sha:
            raise ExecutionError(f"frozen portable consumer changed: {path}")
    manifest = tomllib.loads(sources[FIXTURE / "Cargo.toml"])
    if manifest["package"]["publish"] is not False:
        raise ExecutionError("assurance fixture cannot be published")
    if set(manifest["dependencies"]) != {
        "brynja-sp800185-public-api-fixture", "brynja-crypto-cpu",
        "brynja-hash-parallel", "brynja-hash-parallel-std",
    } or "source =" in sources[FIXTURE / "Cargo.lock"]:
        raise ExecutionError("hosted acceptance dependency closure changed")
    for path, source in sources.items():
        if path.suffix == ".rs":
            if len(source.splitlines()) > 500:
                raise ExecutionError("acceptance source exceeds 500 lines")
            if any(token in source for token in (
                "unsafe {", "for_candidate_evidence", "permute_for_evidence",
                "brynja_cpu_evidence",
            )):
                raise ExecutionError("acceptance bypasses ordinary backend admission")
    for path, token, count in (
        (Path("scripts/checks.sh"), "python3 scripts/sp800185/check-execution-acceptance.py", 1),
        (Path("scripts/checks.sh"), "python3 scripts/sp800185/test-execution-acceptance.py", 1),
        (Path("scripts/ci/check-rust-version-matrix.sh"), "assurance/sp800185-final/Cargo.toml", 1),
        (Path(".github/workflows/ci.yml"), "assurance/sp800185-final/Cargo.toml", 2),
    ):
        if sources[path].count(token) != count:
            raise ExecutionError(f"execution gate coverage changed: {path}")
    if check_hashes:
        document = tomllib.loads(read(root, HASHES))
        actual = {p.as_posix(): digest(s) for p, s in sources.items()}
        if document != {"files": actual}:
            raise ExecutionError("execution acceptance changed; reopen review")


def execute(command: list[str], seconds: int = 300) -> str:
    """Bound trusted fixture tools, not an isolation boundary for hostile code.

    POSIX uses explicitly test-only cooperative process groups; these reviewed
    tools do not detach descendants. Windows uses the existing job-object runner.
    """
    containment = (
        "windows-job-object" if os.name == "nt"
        else "test-only-cooperative-posix-process-group"
    )
    result = run_bounded(
        command, b"", seconds, 2 * 1024 * 1024, containment,
        allow_test_only_containment=True,
    )
    if result.returncode != 0:
        raise ExecutionError(f"acceptance command failed ({result.returncode}): {command[0]}")
    return result.stdout.decode("utf-8", errors="strict")


def check_report(output: str) -> None:
    lines = output.splitlines()
    if any(lines.count(line) != 1 for line in REPORT) or "FAIL" in output:
        raise ExecutionError("execution report is incomplete or contradictory")


def run_fixture() -> str:
    output = execute([
        "cargo", "run", "--quiet", "--locked", "--offline",
        "--manifest-path", str(ROOT / FIXTURE / "Cargo.toml"),
    ])
    check_report(output)
    return output
