#!/usr/bin/env python3
"""Fail-closed v0.24.16 portable SP 800-185 acceptance policy."""

from __future__ import annotations

import hashlib
import subprocess
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
FIXTURE = Path("assurance/sp800185-public-api")
MANIFEST = FIXTURE / "Cargo.toml"
LOCK = FIXTURE / "Cargo.lock"
MAIN = FIXTURE / "src/main.rs"
SOURCES = tuple(sorted((ROOT / FIXTURE / "src").glob("*.rs")))
SOURCE_PATHS = tuple(path.relative_to(ROOT) for path in SOURCES)
HASHES = Path("scripts/sp800185/portable-acceptance-hashes.toml")
FILES = (
    MANIFEST,
    LOCK,
    FIXTURE / "fixtures/representative.txt",
    *SOURCE_PATHS,
    Path("crates/brynja-hash-sha3/tests/cshake.rs"),
    Path("crates/brynja-mac-kmac/tests/official_vectors.rs"),
    Path("crates/brynja-hash-tuple/tests/official_vectors.rs"),
    Path("crates/brynja-hash-parallel/tests/official_vectors.rs"),
    Path("assurance/cshake-public-api/src/lib.rs"),
    Path("assurance/kmac-public-api/src/lib.rs"),
    Path("assurance/tuplehash-public-api/src/lib.rs"),
    Path("assurance/parallelhash-public-api/src/lib.rs"),
    Path("scripts/sha3/check-cshake-differential.py"),
    Path("scripts/kmac/check-kmac-differential.py"),
    Path("scripts/tuplehash/check-tuplehash-differential.py"),
    Path("scripts/parallelhash/check-parallelhash-differential.py"),
    Path("scripts/sp800185/test-portable-acceptance.py"),
    Path("scripts/checks.sh"),
    Path("scripts/ci/check-rust-version-matrix.sh"),
    Path("scripts/assurance/check-bare-metal.sh"),
    Path(".github/workflows/ci.yml"),
    Path("README.md"),
    Path("crates/brynja/README.md"),
    Path("docs/VERIFICATION_STATUS.md"),
    Path("docs/current-status.md"),
    Path("docs/RELEASE_PLAN.md"),
    Path("release-notes/RELEASE_NOTES_0.24.16.md"),
    Path("release-crates.toml"),
)


class PortableAcceptanceError(RuntimeError):
    """The frozen portable SP 800-185 contract differs from policy."""


def fail(message: str) -> None:
    raise PortableAcceptanceError(message)


def read(root: Path, relative: Path) -> str:
    path = root / relative
    if not path.is_file() or path.is_symlink():
        fail(f"portable acceptance input is not a regular file: {relative}")
    return path.read_text(encoding="utf-8")


def require(text: str, token: str, label: str) -> None:
    if token not in text:
        fail(f"{label} drift: {token}")


def require_count(text: str, token: str, expected: int, label: str) -> None:
    actual = text.count(token)
    if actual != expected:
        fail(f"{label} count drift: {token}: expected {expected}, found {actual}")


def write_hashes(root: Path = ROOT) -> None:
    lines = ["# Generated by scripts/sp800185/check-portable-acceptance.py --write.", "[files]"]
    for relative in FILES:
        digest = hashlib.sha256(read(root, relative).encode()).hexdigest()
        lines.append(f'"{relative.as_posix()}" = "{digest}"')
    (root / HASHES).write_text("\n".join(lines) + "\n", encoding="utf-8")


def expected_hashes(root: Path) -> dict[str, str]:
    document = tomllib.loads(read(root, HASHES))
    if set(document) != {"files"} or not isinstance(document["files"], dict):
        fail("portable acceptance hash inventory has invalid shape")
    return document["files"]


def validate(root: Path = ROOT, check_hashes: bool = True) -> None:
    loaded = {relative: read(root, relative) for relative in FILES}
    manifest = tomllib.loads(loaded[MANIFEST])
    expected_package = {
        "name": "brynja-sp800185-public-api-fixture",
        "version": "0.0.0",
        "edition": "2024",
        "rust-version": "1.90",
        "publish": False,
    }
    if manifest.get("package") != expected_package or "workspace" not in manifest:
        fail("portable fixture package identity changed")
    expected_dependencies = {
        "brynja", "brynja-crypto", "brynja-hash-parallel", "brynja-hash-sha3",
        "brynja-hash-tuple", "brynja-mac-kmac",
    }
    dependencies = manifest.get("dependencies", {})
    if set(dependencies) != expected_dependencies:
        fail("portable fixture dependency closure changed")
    if dependencies["brynja"].get("version") != "=0.24.17":
        fail("portable fixture main-facade version changed")
    if dependencies["brynja-mac-kmac"].get("features") != ["conformance-testing"]:
        fail("portable fixture lost exact KMAC conformance coverage")
    if "source =" in loaded[LOCK]:
        fail("portable fixture lockfile contains a registry or git package")
    for relative in SOURCE_PATHS:
        source = loaded[relative]
        if len(source.splitlines()) > 500:
            fail(f"portable fixture source exceeds 500 lines: {relative}")
        if relative != MAIN:
            for forbidden in ("unsafe {", "std::", "alloc::", "extern crate"):
                if forbidden in source:
                    fail(f"portable fixture crossed forbidden boundary: {relative}: {forbidden}")
    library = loaded[FIXTURE / "src/lib.rs"]
    for token in (
        "#![no_std]", "CSHAKE_IMPLEMENTED",
        "KMAC_IMPLEMENTED", "TUPLE_HASH_IMPLEMENTED", "PARALLEL_HASH_IMPLEMENTED",
    ):
        require(library, token, "portable fixture claim")
    for token in (
        "        identities: 14,", "        official_examples: 14,",
        "        hardened_profiles: 14,", "        public_layers: 3,",
    ):
        require_count(library, token, 2, "portable fixture executable claim")
    tokens = {
        FIXTURE / "src/cshake.rs": (
            "cshake128", "cshake256", "HardenedCshake128",
            "let mut state = HardenedCshake256::new",
        ),
        FIXTURE / "src/kmac.rs": (
            "Kmac128", "Kmac256", "KmacXof128", "KmacXof256",
            "Kmac128::new_conformance",
        ),
        FIXTURE / "src/tuplehash.rs": (
            "TupleHash128", "TupleHash256", "TupleHashXof128", "TupleHashXof256",
            "let mut item = fixed.begin_item(48)",
        ),
        FIXTURE / "src/parallelhash.rs": (
            "ParallelHash128", "ParallelHash256", "ParallelHashXof128",
            "parallel_hash_xof256", "ParallelHash128Plan",
            "let plan = ParallelHash256Plan::new",
        ),
    }
    for relative, required in tokens.items():
        for token in required:
            require(loaded[relative], token, f"portable fixture {relative.name}")
    for name in ("cshake", "kmac", "tuplehash", "parallelhash"):
        source = loaded[FIXTURE / f"src/{name}.rs"]
        outputs = ("128", "256") if name == "cshake" else (
            "_fixed128", "_fixed256", "_xof128", "_xof256",
        )
        for output in outputs:
            require_count(
                source, f"if secret.expose() != expected{output} {{", 1,
                f"{name} live hardened output comparison",
            )
    report = loaded[MAIN]
    for token in (
        "SP 800-185 portable public API acceptance: PASS",
        "family status: In progress pending v0.24.17 final acceptance",
        "independently verified: NO", "FIPS 140-3 validated: NO",
    ):
        require(report, token, "portable runnable report")
    for relative in (Path("README.md"), Path("crates/brynja/README.md")):
        require(loaded[relative], "SP 800-185 family | 🚧 In progress", "public status")
        require(loaded[relative], "portable acceptance passed at v0.24.16", "public status")
    require(
        loaded[Path("docs/RELEASE_PLAN.md")],
        "### v0.24.16 - SP 800-185 Portable Public API Usability Acceptance\n\nStatus: released",
        "release-plan status",
    )
    checks = loaded[Path("scripts/checks.sh")]
    for command in (
        "python3 scripts/sp800185/check-portable-acceptance.py",
        "python3 scripts/sp800185/test-portable-acceptance.py",
        "scripts/sha3/check-cshake-differential.py",
        "scripts/kmac/check-kmac-differential.py",
        "scripts/tuplehash/check-tuplehash-differential.py",
        "scripts/parallelhash/check-parallelhash-differential.py",
        "scripts/repository/check-packages.sh",
    ):
        require(checks, command, "repository evidence gate")
    counts = {
        Path("scripts/ci/check-rust-version-matrix.sh"): 1,
        Path("scripts/assurance/check-bare-metal.sh"): 1,
        Path(".github/workflows/ci.yml"): 2,
    }
    for relative, expected in counts.items():
        actual = loaded[relative].count("assurance/sp800185-public-api/Cargo.toml")
        if actual != expected:
            fail(f"portable matrix coverage changed: {relative}: {actual}")
    if check_hashes:
        expected = expected_hashes(root)
        if set(expected) != {path.as_posix() for path in FILES}:
            fail("portable reviewed-hash inventory is incomplete")
        for relative, text in loaded.items():
            if hashlib.sha256(text.encode()).hexdigest() != expected[relative.as_posix()]:
                fail(f"portable reviewed hash drift: {relative}")


def run_fixture(root: Path = ROOT) -> str:
    result = subprocess.run(
        ["cargo", "run", "--quiet", "--locked", "--manifest-path", str(root / MANIFEST)],
        cwd=root,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        timeout=300,
    )
    if result.returncode != 0:
        fail(f"portable SP 800-185 fixture failed:\n{result.stdout}")
    return result.stdout
