[package]
name = "brynja-platform"
version = "0.1.3"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"
description = "Explicit platform integration traits for Brynja"
publish = ["crates-io"]

[features]
default = []


[dependencies]
brynja-core = { workspace = true }

[lints]
workspace = true
