[package]
name = "brynja-pki"
version = "0.1.3"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"
description = "First-party ASN.1, DER, and X.509 validation for Brynja"
publish = ["crates-io"]

[features]
default = []


[dependencies]
brynja-core = { workspace = true }

[lints]
workspace = true
