//! Opaque four-lane NEON MD5 compression; MD5 remains collision-broken.
#![allow(unsafe_code)]

/// Retains packed output only; erases non-output scratch and working registers.
/// Caller packing, output handling and asynchronous interruption are separate.
///
/// # Safety
/// NEON on a little-endian CPU must hold on every eligible CPU during this call.
#[target_feature(enable = "neon")]
#[inline(never)]
pub unsafe extern "C" fn compress(scratch: &mut [u8; 864], constants: &[u32; 80]) {
    // SAFETY: Exact byte regions are initial 0..128, words 128..640, output
    // 640..768 and temporary 768..864. Public counters bound all 64 rounds,
    // message indices 0..16 and shift indices 0..16. Constants are read-only;
    // all scratch accesses are byte-aligned. Only independent packed outputs
    // survive; inactive Arm output halves are zeroed. Computation, scratch
    // erasure and X4/X5/X6, V0..3 erasure stay inside one side-effecting
    // block with no calls, stack accesses or secret Rust outputs. Early clobbers
    // exclude both pointers; flags are erased on normal return.
    unsafe {
        core::arch::asm!(
            "// BRYNJA_SECRET_BEGIN",
            "mov x4, #0",
            "movi v3.16b, #0",
            "2:",
            "add x6, {scratch}, x4",
            "ldr q0, [x6]",
            "str q0, [x6, #640]",
            "str q3, [x6, #656]",
            "add x4, x4, #32",
            "cmp x4, #128",
            "b.ne 2b",
            "mov x4, #0",
            "3:",
            "ldr q0, [{scratch}, #672]",
            "ldr q1, [{scratch}, #704]",
            "ldr q2, [{scratch}, #736]",
            "cmp x4, #16",
            "b.lo 4f",
            "cmp x4, #32",
            "b.lo 5f",
            "cmp x4, #48",
            "b.lo 6f",
            "mvn v2.16b, v2.16b",
            "orr v0.16b, v0.16b, v2.16b",
            "eor v0.16b, v0.16b, v1.16b",
            "lsl x5, x4, #3",
            "sub x5, x5, x4",
            "b 7f",
            "4:",
            "eor v1.16b, v1.16b, v2.16b",
            "and v0.16b, v0.16b, v1.16b",
            "eor v0.16b, v0.16b, v2.16b",
            "mov x5, x4",
            "b 7f",
            "5:",
            "eor v0.16b, v0.16b, v1.16b",
            "and v0.16b, v0.16b, v2.16b",
            "eor v0.16b, v0.16b, v1.16b",
            "add x5, x4, x4, lsl #2",
            "add x5, x5, #1",
            "b 7f",
            "6:",
            "eor v0.16b, v0.16b, v1.16b",
            "eor v0.16b, v0.16b, v2.16b",
            "add x5, x4, x4, lsl #1",
            "add x5, x5, #5",
            "7:",
            "and x5, x5, #15",
            "add x6, {scratch}, x5, lsl #5",
            "ldr q1, [x6, #128]",
            "add v0.4s, v0.4s, v1.4s",
            "ldr q1, [{scratch}, #640]",
            "add v0.4s, v0.4s, v1.4s",
            "add x6, {constants}, x4, lsl #2",
            "ld1r {{v1.4s}}, [x6]",
            "add v0.4s, v0.4s, v1.4s",
            "lsr x5, x4, #2",
            "and x5, x5, #12",
            "and x6, x4, #3",
            "orr x5, x5, x6",
            "add x6, {constants}, x5, lsl #2",
            "ldr w6, [x6, #256]",
            "dup v1.4s, w6",
            "ushl v2.4s, v0.4s, v1.4s",
            "sub w6, w6, #32",
            "dup v1.4s, w6",
            "ushl v0.4s, v0.4s, v1.4s",
            "orr v2.16b, v2.16b, v0.16b",
            "ldr q0, [{scratch}, #672]",
            "add v2.4s, v2.4s, v0.4s",
            "ldr q0, [{scratch}, #736]",
            "str q0, [{scratch}, #640]",
            "ldr q0, [{scratch}, #704]",
            "str q0, [{scratch}, #736]",
            "ldr q0, [{scratch}, #672]",
            "str q0, [{scratch}, #704]",
            "str q2, [{scratch}, #672]",
            "add x4, x4, #1",
            "cmp x4, #64",
            "b.ne 3b",
            "mov x4, #0",
            "8:",
            "add x6, {scratch}, x4",
            "ldr q0, [x6, #640]",
            "ldr q1, [x6]",
            "add v0.4s, v0.4s, v1.4s",
            "str q0, [x6, #640]",
            "add x4, x4, #32",
            "cmp x4, #128",
            "b.ne 8b",
            "movi v0.16b, #0",
            "mov x4, #0",
            "9:",
            "add x6, {scratch}, x4",
            "str q0, [x6]",
            "add x4, x4, #16",
            "cmp x4, #640",
            "b.ne 9b",
            "str q0, [{scratch}, #768]",
            "str q0, [{scratch}, #784]",
            "str q0, [{scratch}, #800]",
            "str q0, [{scratch}, #816]",
            "str q0, [{scratch}, #832]",
            "str q0, [{scratch}, #848]",
            "// BRYNJA_REGISTER_ERASE",
            "mov x4, xzr",
            "mov x5, xzr",
            "mov x6, xzr",
            "movi v0.16b, #0",
            "movi v1.16b, #0",
            "movi v2.16b, #0",
            "movi v3.16b, #0",
            "cmp xzr, xzr",
            "// BRYNJA_SECRET_END",
            scratch = in(reg) scratch.as_mut_ptr(),
            constants = in(reg) constants.as_ptr(),
            out("x4") _,
            out("x5") _,
            out("x6") _,
            out("v0") _,
            out("v1") _,
            out("v2") _,
            out("v3") _,
            options(nostack),
        );
    }
}
