//! Four independent SHA-512 lanes in one opaque AVX2 cleanup boundary.
#![allow(unsafe_code)]

/// Reads packed initial state and 16 message words; retains only work outputs.
/// All addresses use byte alignment; state/message words use native LE order.
///
/// # Safety
/// AVX2 and OS-enabled YMM state must hold on every eligible CPU during this call.
#[target_feature(enable = "avx2")]
#[inline(never)]
pub unsafe extern "C" fn compress(scratch: &mut [u8; 3264], constants: &[u64; 80]) {
    // SAFETY: Exact scratch regions are initial 0..256, schedule 256..2816,
    // work 2816..3072 and temporary 3072..3264. Public bounded loops expand
    // schedule offsets 768..2816 from already initialized preceding words,
    // execute 80 rounds and commit four lanes without mixing SIMD lanes.
    // Everything secret stays in one opaque side-effecting block without stack
    // accesses or calls. All non-output scratch, RAX/RCX/RDX, YMM0..3 and flags
    // are erased before exit. Early clobbers exclude both live input pointers.
    unsafe {
        core::arch::asm!(
            "# BRYNJA_SECRET_BEGIN",
            "xor ecx, ecx",
            "2:",
            "vmovdqu ymm0, [{scratch} + rcx]",
            "vmovdqu [{scratch} + rcx + 2816], ymm0",
            "add rcx, 32",
            "cmp rcx, 256",
            "jne 2b",
            "mov ecx, 768",
            "3:",
            "vmovdqu ymm0, [{scratch} + rcx - 480]",
            "vpsrlq ymm1, ymm0, 1",
            "vpsllq ymm2, ymm0, 63",
            "vpor ymm1, ymm1, ymm2",
            "vpsrlq ymm2, ymm0, 8",
            "vpsllq ymm3, ymm0, 56",
            "vpor ymm2, ymm2, ymm3",
            "vpxor ymm1, ymm1, ymm2",
            "vpsrlq ymm0, ymm0, 7",
            "vpxor ymm1, ymm1, ymm0",
            "vmovdqu [{scratch} + 3072], ymm1",
            "vmovdqu ymm0, [{scratch} + rcx - 64]",
            "vpsrlq ymm1, ymm0, 19",
            "vpsllq ymm2, ymm0, 45",
            "vpor ymm1, ymm1, ymm2",
            "vpsrlq ymm2, ymm0, 61",
            "vpsllq ymm3, ymm0, 3",
            "vpor ymm2, ymm2, ymm3",
            "vpxor ymm1, ymm1, ymm2",
            "vpsrlq ymm0, ymm0, 6",
            "vpxor ymm1, ymm1, ymm0",
            "vpaddq ymm1, ymm1, [{scratch} + 3072]",
            "vpaddq ymm1, ymm1, [{scratch} + rcx - 512]",
            "vpaddq ymm1, ymm1, [{scratch} + rcx - 224]",
            "vmovdqu [{scratch} + rcx], ymm1",
            "add rcx, 32",
            "cmp rcx, 2816",
            "jne 3b",
            "xor ecx, ecx",
            "xor edx, edx",
            "4:",
            "vmovdqu ymm0, [{scratch} + 2816]",
            "vpsrlq ymm1, ymm0, 28",
            "vpsllq ymm2, ymm0, 36",
            "vpor ymm1, ymm1, ymm2",
            "vpsrlq ymm2, ymm0, 34",
            "vpsllq ymm3, ymm0, 30",
            "vpor ymm2, ymm2, ymm3",
            "vpxor ymm1, ymm1, ymm2",
            "vpsrlq ymm2, ymm0, 39",
            "vpsllq ymm3, ymm0, 25",
            "vpor ymm2, ymm2, ymm3",
            "vpxor ymm1, ymm1, ymm2",
            "vmovdqu [{scratch} + 3072], ymm1",
            "vmovdqu ymm0, [{scratch} + 2944]",
            "vpsrlq ymm1, ymm0, 14",
            "vpsllq ymm2, ymm0, 50",
            "vpor ymm1, ymm1, ymm2",
            "vpsrlq ymm2, ymm0, 18",
            "vpsllq ymm3, ymm0, 46",
            "vpor ymm2, ymm2, ymm3",
            "vpxor ymm1, ymm1, ymm2",
            "vpsrlq ymm2, ymm0, 41",
            "vpsllq ymm3, ymm0, 23",
            "vpor ymm2, ymm2, ymm3",
            "vpxor ymm1, ymm1, ymm2",
            "vmovdqu [{scratch} + 3104], ymm1",
            "vmovdqu ymm0, [{scratch} + 2944]",
            "vmovdqu ymm1, [{scratch} + 2976]",
            "vmovdqu ymm2, [{scratch} + 3008]",
            "vpxor ymm1, ymm1, ymm2",
            "vpand ymm0, ymm0, ymm1",
            "vpxor ymm0, ymm0, ymm2",
            "vmovdqu [{scratch} + 3136], ymm0",
            "vmovdqu ymm0, [{scratch} + 2816]",
            "vmovdqu ymm1, [{scratch} + 2848]",
            "vmovdqu ymm2, [{scratch} + 2880]",
            "vpand ymm3, ymm0, ymm1",
            "vpxor ymm0, ymm0, ymm1",
            "vpand ymm0, ymm0, ymm2",
            "vpxor ymm0, ymm0, ymm3",
            "vmovdqu [{scratch} + 3168], ymm0",
            "vmovdqu ymm0, [{scratch} + 3040]",
            "vpaddq ymm0, ymm0, [{scratch} + 3104]",
            "vpaddq ymm0, ymm0, [{scratch} + 3136]",
            "vpaddq ymm0, ymm0, [{scratch} + rcx + 256]",
            "vpbroadcastq ymm1, [{constants} + rdx]",
            "vpaddq ymm0, ymm0, ymm1",
            "vmovdqu [{scratch} + 3200], ymm0",
            "vmovdqu ymm0, [{scratch} + 3072]",
            "vpaddq ymm0, ymm0, [{scratch} + 3168]",
            "vmovdqu [{scratch} + 3232], ymm0",
            "vmovdqu ymm0, [{scratch} + 3008]",
            "vmovdqu [{scratch} + 3040], ymm0",
            "vmovdqu ymm0, [{scratch} + 2976]",
            "vmovdqu [{scratch} + 3008], ymm0",
            "vmovdqu ymm0, [{scratch} + 2944]",
            "vmovdqu [{scratch} + 2976], ymm0",
            "vmovdqu ymm0, [{scratch} + 2912]",
            "vpaddq ymm0, ymm0, [{scratch} + 3200]",
            "vmovdqu [{scratch} + 2944], ymm0",
            "vmovdqu ymm0, [{scratch} + 2880]",
            "vmovdqu [{scratch} + 2912], ymm0",
            "vmovdqu ymm0, [{scratch} + 2848]",
            "vmovdqu [{scratch} + 2880], ymm0",
            "vmovdqu ymm0, [{scratch} + 2816]",
            "vmovdqu [{scratch} + 2848], ymm0",
            "vmovdqu ymm0, [{scratch} + 3200]",
            "vpaddq ymm0, ymm0, [{scratch} + 3232]",
            "vmovdqu [{scratch} + 2816], ymm0",
            "add rcx, 32",
            "add rdx, 8",
            "cmp rdx, 640",
            "jne 4b",
            "xor ecx, ecx",
            "5:",
            "vmovdqu ymm0, [{scratch} + rcx + 2816]",
            "vpaddq ymm0, ymm0, [{scratch} + rcx]",
            "vmovdqu [{scratch} + rcx + 2816], ymm0",
            "add rcx, 32",
            "cmp rcx, 256",
            "jne 5b",
            "xor eax, eax",
            "xor ecx, ecx",
            "6:",
            "mov [{scratch} + rcx], rax",
            "add rcx, 8",
            "cmp rcx, 2816",
            "jne 6b",
            "mov ecx, 3072",
            "7:",
            "mov [{scratch} + rcx], rax",
            "add rcx, 8",
            "cmp rcx, 3264",
            "jne 7b",
            "# BRYNJA_REGISTER_ERASE",
            "vpxor ymm0, ymm0, ymm0",
            "vpxor ymm1, ymm1, ymm1",
            "vpxor ymm2, ymm2, ymm2",
            "vpxor ymm3, ymm3, ymm3",
            "xor eax, eax",
            "xor ecx, ecx",
            "xor edx, edx",
            "cmp eax, eax",
            // Clear the AVX upper-state tracker after all secret working wipes.
            "vzeroupper",
            "# BRYNJA_SECRET_END",
            scratch = in(reg) scratch.as_mut_ptr(),
            constants = in(reg) constants.as_ptr(),
            out("rax") _, out("rcx") _, out("rdx") _,
            out("ymm0") _, out("ymm1") _, out("ymm2") _, out("ymm3") _,
            // VZEROUPPER also writes upper halves of otherwise unused registers.
            // Declare all aliases; the compiler preserves Win64's low XMM6-15.
            out("ymm4") _, out("ymm5") _, out("ymm6") _, out("ymm7") _,
            out("ymm8") _, out("ymm9") _, out("ymm10") _, out("ymm11") _,
            out("ymm12") _, out("ymm13") _, out("ymm14") _, out("ymm15") _,
            options(nostack),
        );
    }
}
